### ISSUE TITLE
Custom folder on Synology: com.synocommunity.packages.cops.ini defaults

### ISSUE THREAD

**Issue by Iciliop** [seblucas/cops#157]
When installing the package on a Synology NAS with the Calibre db in a custom folder the installer correctly detects and updates the path in config_local.php, but ignores the default value for opne_basedir in  /etc/php/conf.d/com.synocommunity.packages.cops.ini 

The values in override the values in com.synocommunity.packages.cops.ini  override the settings in "Control Panel -> Web Services -> Web Applications Customise PHP open_base_dir", so the procedure described in https://github.com/seblucas/cops/wiki/Howto---Synology doesn't fix the problem.

My suggestion id either to automatically set the open_base_dir in com.synocommunity.packages.cops.ini, or to update the How To and the message in checkconfig.php

Thanks a lot for this project!

**Comment by Dr-Bean** [comment]
I've updated the COPS package to 10.0.RC3, and included setting `open_basedir` to `None/Null` (depending on DSM version) and taking it out of the `INSTALL` loop with https://github.com/SynoCommunity/spksrc/commit/c9ae2f6209e94b83009c216f36a9b33f22394423.
That should cover this issue.

@seblucas Not sure if you have a release schedule for a final version of 1.0? There's one other (unrelated) thing I'd want to do before a new release if possible ([this](https://github.com/SynoCommunity/spksrc/pull/1649) with an sc-cops group)

**Comment by seblucas** [comment]
Hi,

Thanks for updating the package, I totally forgot about it.

If all goes well, I'll release 1.0 in July, there's not much to do except for translations update. OffTopic, I'll release the first beta version of COPS's rewrite at the same time, if I want to publish it as a Synology Package, shall I use a new package name ?

Thanks.

**Comment by Dr-Bean** [comment]
Ah, ok. The current changes have not been published yet, but if 1.0 is planned for July, then it still makes sense to publish RC3, timing-wise. I will add the changes I mentioned, and probably correct the COPS wiki too, but I don't know exactly when yet.

I wasn't aware you were rewriting COPS, but I assume that after 1.0, developing that branch will mostly halt? Then, with a published COPS 1.0 package, we simply change `cross/cops` in spksrc to pick up the COPS rewrite, make additional changes where necessary, and publish that as a beta package (result: people with beta enabled get the rewrite, people with beta disabled get stable). If the rewrite is backwards incompatible (mostly wrt config.php, I expect), we can add in a message that an uninstall is required.
Does that work for you?
