### ISSUE TITLE
Cops Synology Package Won't Work

### ISSUE THREAD

**Issue by forepj** [seblucas/cops#168]
Tried everything in how to.  However, I am a novice with the command line.  Have uninstalled for now.  Maybe a shortcoming in the syno community package installer?  Really would love to use the content server.  

error message:

You've been redirected because COPS is not configured properly
Database error
Check if GD is properly installed and loaded
OK
Check if Sqlite is properly installed and loaded
OK
Check if libxml is properly installed and loaded
OK
Check if the rendering will be done on client side or server side
Client side rendering
Check if Calibre database path is not an URL
OK
Check if Calibre database file exists and is readable
File /volume1/books/metadata.db not found, Please check
Value of $config['calibre_directory'] in config_local.php Value of
open_basedir
in your php.ini The access rights of the Calibre Database Synology users please read
this

**Comment by krista611** [comment]
FYI - using an older Synology device (DS410) which only supports up to DSM 5.2 and needed these instructions to configure COPS.  Had to correct the open_basedir in /etc/php/conf.d/com.synocommunity.packages.cops.ini
