### ISSUE TITLE
COPS (1.0.0.RC2-3) package on Synology (DSM 5.1-5004 Update 2) does not work

### ISSUE THREAD

**Issue by new-kirte** [seblucas/cops#182]
Hi,
I've installed COPS following the instructions at https://github.com/seblucas/cops/wiki/Howto---Synology, but when I access the COPS via the HTTP://192.168.1.2/cops I'm redirected to http://192.168.1.2/cops/checkconfig.php?err=1 and see the following:

You've been redirected because COPS is not configured properly
Database error
Check if GD is properly installed and loaded
OK 
Check if Sqlite is properly installed and loaded
OK 
Check if libxml is properly installed and loaded
OK 
Check if Json is properly installed and loaded
OK 
Check if mbstring is properly installed and loaded
OK 
Check if intl is properly installed and loaded
OK 
Check if Normalizer class is properly installed and loaded
OK 
Check if the rendering will be done on client side or server side
Client side rendering 
Check if Calibre database path is not an URL
OK 
Check if Calibre database file exists and is readable
File /volume1/Library/CalibreLibrary/metadata.db not found, Please check 
Value of $config['calibre_directory'] in config_local.php
Value of open_basedir in your php.ini The access rights of the Calibre Database Synology users please read this 

The Calibre library is at /volume1/Library/CalibreLibrary
The config_local.php is as follows:

<?php
    if (!isset($config))
        $config = array();

```
/*
 * The directory containing calibre's metadata.db file, with sub-directories
 * containing all the formats.
 * BEWARE : it has to end with a /
 */
$config['calibre_directory'] = '/volume1/Library/CalibreLibrary/';

/*
 * Catalog's title
 */
$config['cops_title_default'] = "Calibre Library";

/*
 * use URL rewriting for downloading of ebook in HTML catalog
 * See README for more information
 *  1 : enable
 *  0 : disable
 */
$config['cops_use_url_rewriting'] = "0";
```

?>

The open_basedir is (in Control Panel->Web Services->PHP Settings):
/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes:/volume1/Library/CalibreLibrary/

The permissions /volume1/Library/CalibreLibrary/:
http - List folders/Read Data, Read Attributes, Read extended attributes, Read permissions, Create files/Write data, Create folders/Append data, Write attributes, Write extended attributes, Delete subfolders and files

The permissions /volume1/web/cops/:
Everyone - List folders/Read Data, Read Attributes, Read extended attributes, Read permissions

Since it's a new NAS here is what I've done:
1. Enabled Web Station (Control Panel -> Web Services): enabled the following checkboxes:
    - Enable Web Station
- Enable PHP cache
- Customize PHP open_basedir
  - added  :/volume1/Library/CalibreLibrary/ to the end of the string
    - Select PHP extension
      - enabled msssql checkbox
    - Added  http://packages.synocommunity.com to the list of package sources. (Package Center -> Settings)
    - Changed Trust Level from Synology to Synology and trusted publishers  (Package Center -> Settings)
    - Installed COPS package from Community packages (Package Center)
    - During the installation I set  library folder to /volume1/Library/CalibreLibrary/ and library name to "Calibre Library"

Once package has been installed, I've tried it but got the error above. Other packages installed on the NAS: Antivirus Essential, Audio Station, Cloud Sync, Download Station, Media Server, Photo Station, Video Station.

**Comment by itchygrub** [comment]
Dr Bean
Done this but still not working

**Comment by itchygrub** [comment]
Dam 6.2.1-23824 update 6
Ds218play
/volume1/calibre/
Checked permissions has read  all
