### ISSUE TITLE
Visual guidelines :)

### ISSUE THREAD

**Issue by HLFH** [seblucas/cops#185]
Hi,

Could COPS get a logo? It does not seem that it has one for the moment. If COPS was a color, which one would it be? (in hex please). 

Thanks in advance,
HLFH

**Comment by seblucas** [comment]
@HLFH 

Did you have any time to work on it ?

**Comment by HLFH** [comment]
Nope.

**Comment by scorphus** [comment]
I have a colleague that may be interested in contributing. Let's hope she chimes in :smiley:

**Comment by horus68** [comment]
I'm not a master on logo design, but here are some proposals for a logo

option A
![cops_a](https://cloud.githubusercontent.com/assets/3055443/12355261/6aaf72ba-bb93-11e5-8644-151d640b1c8e.png)

option B
![cops_b](https://cloud.githubusercontent.com/assets/3055443/12355264/6ab9c94a-bb93-11e5-8dd4-e5c6ebf52f9f.png)

option C
![cops_c](https://cloud.githubusercontent.com/assets/3055443/12355262/6ab05018-bb93-11e5-820a-607df5818440.png)

option D
![cops_d](https://cloud.githubusercontent.com/assets/3055443/12355263/6ab117f0-bb93-11e5-9ac4-2b0b10b3c655.png)
