### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by aurelazy** [seblucas/cops#191]
Hi all

I don't know if it's the right place where I can post my problem.
I am encounter a problem after the installation, I have this when I enter my URL http://cops.<my_domain>:

You've been redirected because COPS is not configured properly
Database error

All the others options are in the OK state
I checked on the net to find a way but I saw nothing for this.

I run this on a RPi with owncloud and I followed this tuto:
http://www.tolaris.com/2014/04/25/a-better-way-to-share-ebooks-or-my-opds-library-version-2-0/

The other problem is that I don't found log to help.
I thank you so much in advance.
Have a great day, be safe.
Aurélien,

**Comment by seblucas** [comment]
Hi Aurélien,

Can you confirm your PHP version ?
Can you also specify the page : index.php

**Comment by aurelazy** [comment]
Hi Seblucas

Thanks for your answer, and thanks for your apps ;-)
PHP --version ==> PHP 5.4.36-0+deb7u3 (cli)
Here my page index.php (I changed nothing on it):
---------------------------------------------------------------------------
<?php
/**
 * COPS (Calibre OPDS PHP Server) HTML main script
 *
 * @license    GPL 2 (http://www.gnu.org/licenses/gpl.html)
 * @author     Sébastien Lucas <sebastien@slucas.fr>
 *
 */

    require_once ("config.php");
    require_once ("base.php");
    require_once ("author.php");
    require_once ("rating.php");
    require_once ("publisher.php");
    require_once ("serie.php");
    require_once ("tag.php");
    require_once ("language.php");
    require_once ("customcolumn.php");
    require_once ("book.php");
    require_once ("resources/doT-php/doT.php");

    // If we detect that an OPDS reader try to connect try to redirect to feed.php
    if (preg_match("/(MantanoReader|FBReader|Stanza|Marvin|Aldiko|Moon+ Reader)/", $_SERVER['HTTP_USER_AGENT'])) {
        header("location: feed.php");
        exit ();
    }

    $page = getURLParam ("page", Base::PAGE_INDEX);
    $query = getURLParam ("query");
    $qid = getURLParam ("id");
    $n = getURLParam ("n", "1");
    $database = GetUrlParam (DB);


    // Access the database ASAP to be sure it's readable, redirect if that's not the case.
    // It has to be done before any header is sent.
    Base::checkDatabaseAvailability ();

    if ($config ['cops_fetch_protect'] == "1") {
        session_start();
        if (!isset($_SESSION['connected'])) {
            $_SESSION['connected'] = 0;
        }
    }

    header ("Content-Type:text/html;charset=utf-8");

    $data = array("title"                 => $config['cops_title_default'],
                  "version"               => VERSION,
                  "opds_url"              => $config['cops_full_url'] . "feed.php",
                  "customHeader"          => "",
                  "template"              => getCurrentTemplate (),
                  "server_side_rendering" => useServerSideRendering (),
                  "current_css"           => getCurrentCss (),
                  "favico"                => $config['cops_icon'],
                  "getjson_url"           => "getJSON.php?" . addURLParameter (getQueryString (), "complete", 1));
    if (preg_match("/Kindle/", $_SERVER['HTTP_USER_AGENT'])) {
        $data ["customHeader"] = '<style media="screen" type="text/css"> html { font-size: 75%; -webkit-text-size-adjust: 75%; -ms-text-size-adjust: 75%; }</style>';
    }
    $headcontent = file_get_contents('templates/' . getCurrentTemplate () . '/file.html');
    $template = new doT ();
    $dot = $template->template ($headcontent, NULL);
    echo ($dot ($data));
?><body>
<?php
if (useServerSideRendering ()) {
    // Get the data
    require_once ("JSON_renderer.php");
    $data = JSONRenderer::getJson (true);

    echo serverSideRender ($data);
}
?>
</body>
</html>
--------------------------------------------------------------------------

I thank you so much again to take time.
Have a good night.

**Comment by seblucas** [comment]
Can you share your config_local.php and a screenshot of the output of checkconfig.php

Either here or to my email (bottom of README)

**Comment by aurelazy** [comment]
Ok, Je t'envoie un mail ce soir avec les infos.
Passe une bonne journée,

**Comment by seblucas** [comment]
Fixed by mail
