### ISSUE TITLE
Problème avec le lecteur d'epub (epubreader.php)

### ISSUE THREAD

**Issue by andede** [seblucas/cops#192]
Bonjour,

Pour commencer je voudrai remercier tout ceux qui ont participé la conception de ce projet, je ne l'utilise que depuis quelques heures mais il correspond tout a fait à mes besoins.

Mais malheureusement j'ai un petit problème:
Quand j'essayé d'acceder au lecteur d'epub(bouton en forme d'oeil dans les detail d'un ebook), j'obtiens le message d'erreur suivant **"Fatal error: Call to a member function attr() on a non-object in /var/www/COPS/resources/php-epub-meta/epub.php on line 76"**.

Je précise que je n'ai pas modifié le code jusqu'ici.
J'ai hebergé COPS sur un rasberry avec nginx et j'ai normalement installé tous les prérequis.
Au cas ou voici ma configuration pour nginx:
```
server {
    listen 80;
    server_name ebooks.bdgg.be www.ebooks.bdgg.be;
	charset utf-8;
	root /var/www/COPS;
    index index.php;
	
	location ~ \.php$ {
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
    }
	
	location ~ .(js|css|eot|svg|woff|ttf)$ {
                expires 31d;
    }
}
```
Et voici ma configuration pour COPS:
```
<?php
    if (!isset($config))
        $config = array();
 
    $config['calibre_directory'] = '/var/www/COPS/BIBLIO/';

    $config['cops_title_default'] = "BDGG";
    
    $config['cops_use_url_rewriting'] = "0";

	$config['cops_prefered_format'] = array ("EPUB", "PDF","MOBI");
	
	$config['cops_template'] = 'bootstrap';
	
    $config['cops_update_epub-metadata'] = "1";
```
Vous pouvez acceder a mon COPS à l'adresse www.ebooks.bdgg.be

Pouvez-vous m'aider à corriger problème?

**Comment by seblucas** [comment]
Bonjour,

Vu le style de l'erreur, c'est possible que cela vienne du fichier epub.

Est ce que le problèmes se produit avec tous les fichiers EPUB ?
Est ce que les fichiers qui posent problème sont valides (http://validator.idpf.org/) ?

**Comment by andede** [comment]
Effectivement l'ebook n'était pas valide. Le lecteur fonctionne parfaitement avec les ebooks valide.
Merci et désolé pour le derangement.
