### ISSUE TITLE
Cannot use email function from kindle

### ISSUE THREAD

**Issue by chadberg** [seblucas/cops#194]
When trying to use the email to address function from my kindle, the kindle tries to load 'empty.php' which doesn't actually exist, so generates a 404.

I suspect the Kindle is being too literal here.  But it blocks the send to email option.

**Comment by seblucas** [comment]
Hi,

Can you share your config_local.php (here or by mail) and try to add this line in it : 

`$config['cops_server_side_render'] = "";`

**Comment by chadberg** [comment]
Here it is with some redactions.  I'll add the line mentioned and try again.

If relevant, I am using nginx.

<?php
    if (!isset($config))
        $config = array();

	$config['cops_full_url'] ='************'; 
  
    /*
     * The directory containing calibre's metadata.db file, with sub-directories
     * containing all the formats.
     * BEWARE : it has to end with a /
     */
    $config['calibre_directory'] = '/home/calibre/Calibre/';
    $config['calibre_internal_directory'] = '/Calibre/';
    $config['cops_basic_authentication'] = array('username'=>'**********', 'password'=>'***********');
    /*
     * Catalog's title
     */
    $config['cops_title_default'] = "Chad's Library";
    
    /*
     * use URL rewriting for downloading of ebook in HTML catalog
     * See README for more information
     *  1 : enable
     *  0 : disable
     */
    $config['cops_use_url_rewriting'] = "1";
    $config['cops_x_accel_redirect'] = "X-Accel-Redirect";
    $config['default_timezone'] = "America/New_York";
    $config['cops_prefered_format'] = array ("MOBI", "EPUB", "PDF", "AZW3");
   /* $config['cops_calibre_custom_column'] = array ()*/
    $config['cops_mail_configuration'] = array ("smtp.host"     => "smtp.gmail.com",
                                                "smtp.username" => "chadberg@gmail.com",
                                                "smtp.password" => "***********",
                                                "smtp.secure"   => "ssl",
						"smtp.port"	=> "465",
						"address.from"  => "chadberg@gmail.com"
                                                );

**Comment by chadberg** [comment]
Adding the server side render config line made no difference.

**Comment by seblucas** [comment]
Ok :(

Can you try checkconfig.php to check if you're using client or server side rendering ?
Can you also tell me what's your Kindle model ?

**Comment by chadberg** [comment]
Logging in from my desktop, it says client side. Checking from my Kindle Paperwhite, it says server side.

**Comment by seblucas** [comment]
Sorry for the delay ...

It shouldn't say server side on the kindle with `$config['cops_server_side_render'] = "";`

Can you check ?

**Comment by chadberg** [comment]
And yet, it does.  config_default.php says:
>$config['cops_server_side_render'] = "Kindle|EBRD1101|EBRD1201|cybook";

but config_local.username.php has:
>$config['cops_server_side_render'] = "";

and from the Kindle it says Server side rendering.

If I take out all the strings from the config_default, it still says server side from the Kindle, so somewhere it isn't even checking the config setting?

I also tried commenting out the Kindle specific code brought in through commit 3aebffc for a lark, but that didn't help.

grep'd my files for 'render' and didn't see any place where this setting was inadvertently set.

Looking at my nginx logs, the user agent string for my kindle is:
>"Mozilla/5.0 (X11; U; Linux armv7l like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+"

**Comment by seblucas** [comment]
I'm too tired, sorry :( my previous suggestion was not correct !

Could you try with `$config['cops_server_side_render'] = "zzzzzzzz";`

**Comment by chadberg** [comment]
Putting it in config_local.username didn't work (That's probably on my end to look at), but putting it into config_default did give the hoped for client side rendering.

And with that the email function did exactly as it should.

**Comment by seblucas** [comment]
Thanks.

If you can confirm that COPS works fine with client side rendering, I'll remove it from the exception on the next release.

**Comment by chadberg** [comment]
It seems to be working just fine.  I'll want to uncheck the lightbox fancyapps (although they work, the separate page is preferred on this screen).

**Comment by seblucas** [comment]
Thanks I'll be commiting a proper fix soon.
