### ISSUE TITLE
 suggestion: sort "most recent" for whole library

### ISSUE THREAD

**Issue by dosser** [seblucas/cops#195]
sorting the whole library by "most recent" should be implmented asap.

only 50 "most recent" books isn't practicable at all.

**Comment by seblucas** [comment]
Thanks, patches are always welcome ;)

**Comment by alexzeitgeist** [comment]
I haven't had time to clean up my branches yet and to do pull requests, but you can have a look here for a working patch:

https://github.com/alexzeitgeist/cops/commit/44cb8509a31f2f101fcccd3604262ba4450b5a2e
