### ISSUE TITLE
Database not found

### ISSUE THREAD

**Issue by arennuit** [seblucas/cops#198]
Hi,

I have installed COPS on synology DSM 5 but whatever I do I get a "Database error" saying metadata.db is not found. COPS version is 1.0.0RC2-3 from the package center.

![image](https://cloud.githubusercontent.com/assets/8360384/6428122/82b0168a-bf95-11e4-914d-9dbeec2ea4a9.png)

Obviously my database is exactely where indicated.

My config_local.php looks like the following

```php
<?php
    if (!isset($config))
        $config = array();
    /*
     * The directory containing calibre's metadata.db file, with sub-directories
     * containing all the formats.
     * BEWARE : it has to end with a /
     */
    $config['calibre_directory'] = '/volume1/homes/arennuit/CloudStation/Books/Romans_nouvelles_contes/';
    
    $config['calibre_internal_directory'] = '/volume1/homes/arennuit/CloudStation/Books/Romans_nouvelles_contes/';
    $config['cops_x_accel_redirect'] = "X-Sendfile";
    
    /*es/web:/var/services/homes:
     * Catalog's title
     */
    $config['cops_title_default'] = "COPS";
    
    /*
     * use URL rewriting for downloading of ebook in HTML catalog
     * See README for more information
     *  1 : enable
     *  0 : disable
     */
    $config['cops_use_url_rewriting'] = "0";
?>
```

I have also tried with `$config['cops_use_url_rewriting'] = "0";`

I have added `:/volume1/homes/arennuit/CloudStation/Books/Romans_nouvelles_contes` and `:volume1/web/cops` to *open_basedir* in the control panel.

I have updated */etc/httpd/conf/httpd.conf-user*

with 

```
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_dbm_module modules/mod_authn_dbm.so
LoadModule authn_anon_module modules/mod_authn_anon.so
LoadModule authn_dbd_module modules/mod_authn_dbd.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_dbm_module modules/mod_authz_dbm.so
LoadModule authz_owner_module modules/mod_authz_owner.so
LoadModule auth_digest_module modules/mod_auth_digest.so
```

as indicated [here](http://www.mobileread.com/forums/showpost.php?p=2785262&postcount=824) - though I do not understand what **You can try checking the "mssql" checkbox** means.

I have changed the rights of file */volume1/homes/arennuit/CloudStation/Books/Romans_nouvelles_contes/metadata.db* to **rwxrwxrwx** and its owner to **http:http**.

And obviously I have restarted the NAS several times.

And despite of all my efforts I still have the same error... Did I forget anything or is there a bug?

Links used:
[link1](http://blog.slucas.fr/blog/cops-nas-synology)
[link2](http://blog.slucas.fr/blog/cops-spk-available)
[link3](http://lo-ol.fr/pluxml/index.php?article11/calibre-et-cops-pour-gerer-ses-ebooks)
[link4](https://github.com/seblucas/cops/wiki)

Regards,

Antoine.

**Comment by seblucas** [comment]
Hi,

Unfortunately, DSM forbid any web application (like COPS) to access of /volumeX/homes. You have two choices : 
 * Create a new share outside of homes
 * Try to mount --bind (try google) you homes directory.

I haven't checked the FAQ, could check and add an entry about that please.
