### ISSUE TITLE
Custom column view fails

### ISSUE THREAD

**Issue by doug-w** [seblucas/cops#200]
I have a custom column that in my config_local.php is declared as:

`$config['cops_calibre_custom_column'] = array ("gr_2read");`

It's defined in the database as:

4|gr_2read|2Read|bool|0|1|{}|0|0

When I look at the main page I see a '2Read' section as expected, but clicking on it errors with:

2015/03/09 04:11:25 [error] 32#0: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function fetchObject() on a non-object in /var/www/customcolumn.php on line 92" while reading response header from upstream, client: X.Y.Z.W, server: localhost, request: "GET /getJSON.php?page=14&custom=4&_=1425874474105 HTTP/1.1"

First, should it page 14 for clicking through?  That's PAGE_ALL_CUSTOMS.  I'd think it should be PAGE_CUSTOM_DETAIL instead?  But even trying that fails with:
2015/03/09 04:25:55 [error] 32#0: *30 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getEntryId() on a non-object in /var/www/base.php on line 745" while reading response header from upstream, client: X.Y.Z.W, server: localhost, request: "GET /getJSON.php?page=15&custom=4&complete=1&_=1425875347915 HTTP/1.1"

The count of the field is correct, but going into the view just fails in all cases.  This is from downloading 1.0.0RC3.tar.gz from github directly.

**Comment by seblucas** [comment]
Can you share your metadata.db and your config by mail (if possible). I have a unit test about it so it should work.

Thanks in advance.

**Comment by doug-w** [comment]
Thanks,  

I've sent it.  I did see the tests but they looked like they were enumerating the names of the columns, not the contents of it.  However, I hadn't had time to set up a php dev environment to actually debug it.

**Comment by seblucas** [comment]
The good news is I've reproduced it with your database. The bad news is that there must have a change in Calibre for the custom columns. Can you confirm your Calibre version ?

**Comment by doug-w** [comment]
It's 2.1 now, but the database has been around forever, at least a pre 1.0.  Any migrations in place?  I could just drop all columns to see if it regenerates the new ones with the current schema as it's a plugin that creates the data for those columns (Good read shelf syncing)

**Comment by chadberg** [comment]
Any followup on this? I'm having the same issue, I believe.

**Comment by doug-w** [comment]
I believe this was tracked down to having an ancient database that went through dozens of auto-migrations.  In the end it wasn't worth it for me tracking down what went right/wrong, and I just blew away the DB and recreated it in Calibre.

**Comment by chadberg** [comment]
Alright, thanks! Off to do a https://manual.calibre-ebook.com/generated/en/calibredb.html#restore-database
