### ISSUE TITLE
Blank page issue

### ISSUE THREAD

**Issue by rcspam** [seblucas/cops#201]
Hi,
I have installed cops in my /var/www directory.
Apache2 is my server on ubuntu 14.04.
I have add the calibre library path in config_local.php.

A "http://127.0.0.1/cops/checkconfig.php" says that's all is ok !
But "http://127.0.0.1/cops/" or "http://127.0.0.1/cops/index.php" give a blank page and and nothing else.

I have the Ubuntu standard install of apache2.
Apache2 works because "http://127.0.0.1/html" give me the right html apache page.
I'm not an apache expert so....
Someone can light me ?

Regards

**Comment by rcspam** [comment]
I can add this clarification...

A 'tail f /var/log/apache2/error.log' write the following error:
PHP Fatal error:  require_once(): Failed opening required 'resources/php-epub-meta/epub.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/cops/book.php on line 18

**Comment by rcspam** [comment]
Apologies for closing

**Comment by seblucas** [comment]
It's really strange. 
What's your PHP version ?
Can you check if the user running apache have read access to the resources directory ?

**Comment by rcspam** [comment]
PHP Version 5.5.9
I have test a phpinfo.php in the cops dir and it works !
Yes all user have a read access to the dir !!

**Comment by seblucas** [comment]
Can you check tour open_basedir in php.ini.

Besides that I don't know what's happening

**Comment by rcspam** [comment]
"open_basedir option" in
/etc/php5/apache2/php.ini, /etc/php5/cli/php.ini, /etc/php5/fpm/php.ini
 and /etc/php5/cgi/php.ini:

; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file. This directive is
; *NOT* affected by whether Safe Mode is turned On or Off.
; http://php.net/open-basedir
;open_basedir =

are all commented.

I dont know if it's right.
Is it ?


2015-03-19 8:13 GMT+01:00 Sébastien Lucas <notifications@github.com>:

**Comment by rcspam** [comment]
I've found: just a right issue
a 'chmod' command line has resolved this issue... ;)

**Comment by iostrym** [comment]
do you remember what was the directory that cause the problem ? because I have same problem than you. I did chmod -R 777 on the database directory and it makes working the checkconfig.php but I still have a blank page when accessing to http://192.168.1.50/cops
Any idea ?

**Comment by rcspam** [comment]
@iostrym , sorry for the late answer, but no i don't remember what parameters with the chmod command i made... I don't use Cops anymore so i can help you. Sorry
