### ISSUE TITLE
HTML symbol entities in links break some OPDS clients

### ISSUE THREAD

**Issue by jasio2** [seblucas/cops#202]
I am trying to access my OPDS catalog managed by COPS from the KOReader client. I tried both Kindle and Kobo. But when I try to download a book it downloads the cover instead.
I have found that in the XML reply to a request like `/cops/feed.php?page=10` there are HTML entities in the URLs, `&amp;` instead of `&`.

`<link href="fetch.php?data=617&amp;type=epub&amp;id=214" type="application/epub+zip" rel="http://opds-spec.org/acquisition" title="EPUB"/>`

I would expect the link to look like this:
`<link href="fetch.php?data=617&type=epub&id=214" type="application/epub+zip" rel="http://opds-spec.org/acquisition" title="EPUB"/>`

Some clients seem to be able to convert it back before making a request. I have checked the feeds from a few online catalogs like manybooks.net and the URLs are clean, using simple & characters.

**Comment by seblucas** [comment]
Sorry for my late answer. IIRC HTML entities are mandatory for the full OPDS compliance. I'll check that.

In the meantime if you had time to check the few online catalog against https://opds-validator.appspot.com/ it would be great.

Thanks in advance.

**Comment by jasio2** [comment]
Hi 

I'll check the validator on a few catalogs when I come back from
holidays. Nothing urgent in the mean time. 

Thanks, 

Yann 

---
 Yann Muller - yann@darkriver.net
 http://darkriver.net

On 2015-04-01 17:24, Sébastien Lucas wrote: 

> Sorry for my late answer. IIRC HTML entities are mandatory for the full OPDS compliance. I'll check that. 
> 
> In the meantime if you had time to check the few online catalog against https://opds-validator.appspot.com/ [1] it would be great. 
> 
> Thanks in advance. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://opds-validator.appspot.com/
[2] https://github.com/seblucas/cops/issues/202#issuecomment-88522063

**Comment by seblucas** [comment]
I tested the OPDS validator with this url : http://cops-demo.slucas.fr/feed.php?page=3&id=1

everything is ok, as soon as I replace one `&amp;` by `&` I have this error

`The reference to entity "XXX" must end with the ';' delimiter.`

So I'm closing it. Please reopen if you can proove that the validator is wrong.

Have a good holidays ;).
