### ISSUE TITLE
PHP Fatal error:  Call to a member function fetchColumn()

### ISSUE THREAD

**Issue by rogc** [seblucas/cops#206]
I followed the Howto PhpEmbeddedServer, but after the browser request this is the error log:

[Thu Apr 23 17:29:10 2015] PHP Fatal error:  Call to a member function fetchColumn() on a non-object in /var/www/cops/base.php on line 1330
[Thu Apr 23 17:29:10 2015] 192.168.1.5:55835 [500]: /getJSON.php?complete=1&_=1429802949033 - Call to a member function fetchColumn() on a non-object in /var/www/cops/base.php on line 1330

**Comment by ICDeadPpl** [comment]
I get the same error with COPS 1.0.0RC3, on Apache 2.4.7 with PHP 5.5.9:
PHP Fatal error: Call to a member function fetchColumn() on a non-object in /app/cops/base.php on line 1265
