### ISSUE TITLE
Blank page on Kindle 4

### ISSUE THREAD

**Issue by silviuvulcan** [seblucas/cops#208]
Hi,

I kept wanting to find out what changed that broke cops on my kindle and today I had the time to dig around. I have a Kindle 4 (the cheap one from some years ago) and cops was working fine in the past. I tracked down the issue to 8c982fd. 

My kindle shows a blank page with this patch but if I add Kindle 3.0 to the regex starts working again. My UA string is: 
```"Mozilla/5.0 (Linux; U; en-US) AppleWebKit/528.5+ (KHTML, like Gecko, Safari/528.5+) Version/4.0 Kindle/3.0 (screen 600x800; rotate)"```

**Comment by seblucas** [comment]
Hi,

Kindles are very strange ... I've had reports of COPS working even on old Kindles with client side rendering .... Maybe it works fine only with Kindle PaperWhite. I'll fix it in the next version.
