### ISSUE TITLE
Feature Request: Series sub-levels when viewing by author

### ISSUE THREAD

**Issue by ki5ck** [seblucas/cops#214]
Not sure if this has ever been discussed, but is it possible to add series under the authors as another sublevel? Perhaps have stand-alone books in that top level or another sublevel called "novels" or some such?

I have several authors with many, many books and it would be nice to see the series on their own level, along with the series number (so I don't have to count down 19 entries or see at a glance if something is missing).

**Comment by seblucas** [comment]
Sorry for the delay, for now IIRC the list is sorted by series so the book are grouped by series but there's no graphical hint to show a series change

I'll think about it in the rewrite I'm doing

**Comment by ki5ck** [comment]
Thank you kindly, sir.

**Comment by seblucas** [comment]
Done in the rewrite. I'll close it
