### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by ibmiiste** [seblucas/cops#217]
Bonjour, 

Depuis peu, dans Moon+ Reader, quand j'accède à mon cops via les catalogues, j'ai le message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

Par contre, cela fonctionne très bien sur le site de démo:http://cops-demo.slucas.fr/feed.php

Cordialement, 

Ibmiiste.

**Comment by seblucas** [comment]
Bonjour,

As tu fait l'essai avec un autre client OPDS (FBReader par exemple)

Y a-t-il eu une mise à jour de Moon+ ?

**Comment by ibmiiste** [comment]
Bonjour, 

Après plusieurs essais, c'est revenu à la normale après avoir réinitialisé Moon+ Reader Pro. 

Çà ne fonctionnait pas sur la version installée sur le téléphone cependant cela marchait sur la version tablette.

Apparemment quand Moon+ reader "pense" qu'il s'agit d'une page web, il ouvre l'adresse dans son navigateur, d'où le message.

Cordialement, 

Ibmiiste.
