### ISSUE TITLE
Class 'DOMXPath' not found

### ISSUE THREAD

**Issue by df-cryptostorm** [seblucas/cops#218]
From a default CentOS nginx setup:

PHP Fatal error:  Class 'DOMXPath' not found in /usr/share/nginx/html/resources/php-epub-meta/epub.php on line 775 

Looks like aside from php-gd and php-sqlite3, a `yum install php-xml` is also needed before the initial checkconfig.php will parse.

**Comment by seblucas** [comment]
Indeed the packages are embedded for Debian and Ubuntu
