### ISSUE TITLE
Cream Templates

### ISSUE THREAD

**Issue by blazejos** [seblucas/cops#224]
I have problem with app wasn't show anything when have acces to database not even error. Only comunicate was that in index.php on line 60 cream template is missing. I can't find why but when I copied base template to new folder: "cream" all is working correctly  now so that is temporary solution before you found where is this hardcoded call to "cream" obsolete template.

**Comment by seblucas** [comment]
Try to clear all your cookies related to cops.

I never hearded of a template named cream so I really don't know where it come from !
