### ISSUE TITLE
COPS on Synology DSM 5.2, database not found

### ISSUE THREAD

**Issue by rboele** [seblucas/cops#227]
Am running COPS (1.0.0RC2-3) on a Synology Diskstation with the latest DSM (5.2-5644),
noted that the cops database that was running before wasn’t found anymore.
Indicated in Package Center, COPS was still running fine.

Messages:
- You've been redirected because COPS is not configured properly
Database error
- Check if Calibre database file exists and is readable
File /volume1/calibre/metadata.db not found, Please check

Tried several things, mentioned at
https://github.com/seblucas/cops/wiki/Howto---Synology

but this did it:

Control Panel > Shared Folder > Edit folder ‘calibre’ > Permissions

Local users: ‘$user’ enable Read only 
Local groups: ‘http’  enable Read Only

For the wiki, cheers, Rolf

**Comment by xila76** [comment]
Doesn't work for me... Same error message but solution with permissions not working...

**Comment by xila76** [comment]
Solved the problem was the metadata.db who I haven't move when I moved my library to NAS...
