### ISSUE TITLE
How to display public static icons

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#228]
On the image files here: https://github.com/seblucas/cops/tree/master/images
It looks like they only display in the feed, not the actual main page (web view)
How can I display them in the main page?

Note: File base.php do show this code to images:
```
    public static $icons = array(
        Author::ALL_AUTHORS_ID       => 'images/author.png',
        Serie::ALL_SERIES_ID         => 'images/serie.png',
        Book::ALL_RECENT_BOOKS_ID    => 'images/recent.png',
        Tag::ALL_TAGS_ID             => 'images/tag.png',
        Language::ALL_LANGUAGES_ID   => 'images/language.png',
        CustomColumn::ALL_CUSTOMS_ID => 'images/tag.png',
        "cops:books$"             => 'images/allbook.png',
        "cops:books:letter"       => 'images/allbook.png',
        Publisher::ALL_PUBLISHERS_ID => 'images/publisher.png'
    );
```
my config_default.php has proper
```
    /*
     * Show icon for authors, series, tags and books on OPDS feed
     *  1 : enable
     *  0 : disable
     */
    $config['cops_show_icons'] = "1";
```
(no line related in config_local.php )

How can I display those images next to the categories entry on main page?
If I can get this to work maybe its also an easy way to solve my feature request:
https://github.com/seblucas/cops/issues/222

**Comment by seblucas** [comment]
These icon are only shown in the OPDS stream. I've added some icons in the bootstrap template.
