### ISSUE TITLE
metadata.db not readable

### ISSUE THREAD

**Issue by jmt-cash** [seblucas/cops#229]
Hello,
I am using COPS v1.0RC3 on a Raspi. The Library is located on a NAS and the Raspi loads it via SMB Mount. The share is just readable to the Raspi, not writable, but COPS says "metadata.db not readable. What can I do?

Ilu

**Comment by seblucas** [comment]
Are you sure that the user www-data has read rights to this database ?

**Comment by jmt-cash** [comment]
Am 21.12.2015 um 14:25 schrieb Sébastien Lucas:
> Are you sure that the user www-data has read rights to this database ?

I mount the whole folder via SMB from my NAS. On the NAS, everyone may 
read the file.

Yours
Tobias

**Comment by seblucas** [comment]
Hi can you check to access your file on your raspberry pi with the right access rights. Something like that (as root) : 
```
su - www-data
ls /media/yourshare/calibre/metadata.db
```

**Comment by auspex** [comment]
if that _looks_ OK, i'd install the `sqlite3` package, and try:

    sudo -u www-data sqlite3 /PATH/TO/metadata.db "select * from books"

**Comment by jmt-cash** [comment]
Thanks for all the tips. I will try them and report back! ;-)

Am 09.01.2016 um 15:24 schrieb Derek Broughton:

**Comment by jmt-cash** [comment]
Thanks for your help. It really was a permissions problem. As both 
systems are Linux based, the client inherited the permissions' 
configuration 700 from the server, but the user was not the same, so 
www-data was not able to read the database.

Have a nice evening!

Tobias

Am 09.01.2016 um 15:24 schrieb Derek Broughton:
