### ISSUE TITLE
OPDS reader identification

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#236]
How to identify ebook reader apps (android) to redirect to feed.php ?
Main index.php now includes this ones:
MantanoReader|FBReader|Stanza|Marvin|Aldiko|Moon+ Reader|Chunky

```
    // If we detect that an OPDS reader try to connect try to redirect to feed.php
    if (preg_match("/(MantanoReader|FBReader|Stanza|Marvin|Aldiko|Moon+ Reader|Chunky)/", $_SERVER['HTTP_USER_AGENT'])) {
        header("location: feed.php");
        exit ();
    }
```

I'm looking for the proper names for these apps:

FullReader+ https://play.google.com/store/apps/details?id=com.fullreader

PocketBook reader https://play.google.com/store/apps/details?id=com.obreey.reader

Ebookdroid https://play.google.com/store/apps/details?id=org.ebookdroid

Note: I was able to identify this one as "AlReader" (and will make a PR for it)
AlReader - https://play.google.com/store/apps/details?id=com.neverland.alreader

**Comment by seblucas** [comment]
The problem is that they do not advertise their HTTP_USER_AGENT

So I added the ones I could test myself (Android apps : FBReader, Mantano, Aldiko, Moon+Reader) and used PR for the ones I cannot test (Stanza, Marvin, Chunky, ....)

To check their HTTP_USER_AGENT, the easy way is to enable your webserver logs (on Nginx, Apache, ...), connect your OPDS app to your catalog  and you'll find the user agent in the log.

**Comment by horus68** [comment]
I'm on a shared host. 
The php_error.log available to me do not show any error!

**Comment by seblucas** [comment]
That information is not available in the php_error.log. You'll have it in the access.log of the webserver you're using (should be apache). I think some shared hosting also give access to the access log.

**Comment by seblucas** [comment]
If you can't have access to this file. Your best option is to modify feed.php to log the User Agent to a file.

**Comment by horus68** [comment]
I don't know how to do that (not a coder). Maybe you can create it to me and past it to http://pastebin.com/
I will make the PR for those apps as a retribution!

**Comment by seblucas** [comment]
Ok, I've not tested this, but you can try to add this line in the beginning of feed.php or index.php : 

```
file_put_contents("logUA.txt", $_SERVER['HTTP_USER_AGENT'] . "\n", FILE_APPEND);
```

You'll get the user agent in the file `logUA.txt`. Some share hosting forbid the use of `file_put_contents` so you may have an error.

**Comment by horus68** [comment]
Working. See Push release!
