### ISSUE TITLE
Published date not displayed when before 13 December 1901

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#245]
I don't know if its Calibre or Cops but a book with published date 14/december/1901 displays the date on COPS. If published date is 13/december/1901 the date do not show up

![2016-01-14 20_29_33-000581-editar metadados - the book of dragons - 10 de 14](https://cloud.githubusercontent.com/assets/3055443/12336926/135a61da-baff-11e5-8fda-5f0e232b74d9.png)

![2016-01-14 20_30_10-000582-ingles](https://cloud.githubusercontent.com/assets/3055443/12336930/1679921e-baff-11e5-856d-919da4eff42a.png)

So how is to blame and how to solve this?

And for the fun it seems 1 jan is not a good date!

1 Jan 1903 shows up as 1902 ... 
1 Jna 1905 shows up as 1903 ... 
![2016-01-14 20_11_49-000578-editar metadados - the book of dragons - 10 de 14](https://cloud.githubusercontent.com/assets/3055443/12337112/fe34c5d8-baff-11e5-8640-684be1408f5b.png)

**Comment by seblucas** [comment]
It is a bug in COPS, I saw it a few month ago when I was working on COPS 2.0, I'll hack the fixed version and merge it ASAP.
