### ISSUE TITLE
[1.0.0RC3] Mantano Reader (Android) troubles

### ISSUE THREAD

**Issue by vincowl** [seblucas/cops#247]
I have manually installed 1.0.0RC3 on a Synology DSM212+ DSM 5.2-5644 Update 1
It works perfectly in a web browser (search / download)
I tried to link it to my android device using mantano reader. I can't manage to have the odds content displayed. Instead it display a kind of log file (?). The http://cops-demo.slucas.fr/feed.php works perfectly... My cops instance is perfectly displayed in Moon+ Reader but downloads fail. The same cops instance is also perfectly displayed in Mantano on IOS but downloads fails...

Here is my config_local.php
```php
<?php
    if (!isset($config))
        $config = array();
    $config['calibre_directory'] = '/volume1/xxxxx/';
    $config['calibre_internal_directory'] = '';
    $config['cops_full_url'] = 'http://xxx.yyy.fr/';
    $config['cops_title_default'] = "COPS";
    $config['cops_use_url_rewriting'] = "0";
    $config['cops_x_accel_redirect'] = "";
    $config['cops_generate_invalid_opds_stream'] = "0";
```
I configured Mantano using http://xxx.yyy.fr/ as opds server url (same behavior using *http://xxx.yyy.fr/feed.php*)
Here is Mantano's display:
![screenshot_2016-01-19-23-14-18](https://cloud.githubusercontent.com/assets/16786457/12433635/7309afa8-bf02-11e5-99db-34a625c5cdcd.png)

**Comment by seblucas** [comment]
Hi,

That's strange. I have to admit that I don't use Mantano anymore (it was my preferred app a year ago, I use FBReader now). Can you try to add `http://cops-demo.slucas.fr/feed.php` to your OPDS feed to confirm the problem comes from your server and not from COPS ?

Thanks in advance.

**Comment by seblucas** [comment]
Ping ;) ?

**Comment by vincowl** [comment]
Sorry for the delay... The cops demo link works perfectly. I've just found the trick to make my cops instance behave normally. I had a remaining installation of cops syno package. Once removed, everything works like a charm using php or .htaccess identification. Download and browsing are working perfectly using Mantano and DSM 5.0. I still can't manage to have it working in Moon+ Reader despite of the cops_generate_invalid_opds_stream activation... Instead I have an error displaying the raw XML and a message saying it can not found any stylesheet... Strange ! Nevermind, mantano is perfect to me right now. I may have a look at FB reader...
So I think issue can be closed !
