### ISSUE TITLE
Protected multi user access

### ISSUE THREAD

**Issue by vincowl** [seblucas/cops#248]
Hi,
Is there a way to declare multi users password using PHP protection ? If so, is there a way to have dedicated sessions ? I am trying to share my calibre library to several users who may read online the same book. Cops should remember where each user ended its reading. Maybe using a kind of C++ multimap ?? (sorry I am not really accustomed to PHP...). 
Thanks for your help !!!

**Comment by horus68** [comment]
I think you are pushing the COPS way of work. COPS is an OPDS server for your books and is better that it stays simple and do what its supposed to do.
You better share your library link to your users. Then they should install a reader app where they will link to COPS. There they can download books to read and have all features required by readers.
So its not the server that should have features... is the reader that should have programs to read.
Example: If you are on android try the apps PocketBook Reader https://play.google.com/store/apps/details?id=com.obreey.reader or Moon+ reader https://play.google.com/store/apps/details?id=com.flyersoft.moonreader
There you can link to the library (as an external catalog / library)

**Comment by vincowl** [comment]
That's exactly the way I am using dit : through Mantano Reader. Cops offers
to read books online as well as it serves them through readers (button view
or eBook format). It also provides a way to protect your library through a
login / password pair. As you read your books online, it stores the
information of your reading progression. So why would it be out of scope to
store this information linked to different users ? Online reading is the
feature who made the difference among others solutions. Maybe I am not
looking for the right kind of solution approach ?? So what should I be
looking for ? Any ideas ?

**Comment by seblucas** [comment]
Hi,

It's a nice idea of course but I won't do anything related to that soon.

For now reading progression is saved in a browser cookie so it's not related to the user / password, only the browser. There's really a lot of work to do to make it work as you propose.

**Comment by vincowl** [comment]
OK !... So if progression is stored in a cookie, I just have to consider
the login / password as a unique key to my bookstore and share it. No need
to protect special areas for me.
So that fits me perfectly well as is. Thanks !!
Le 29 janv. 2016 15:24, "Sébastien Lucas" <notifications@github.com> a
écrit :
