### ISSUE TITLE
HTTP Error 404.11 – URL_DOUBLE_ESCAPED and security issues on IIS server

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#249]
IIS 7.x server do not allow + signs in URL (or Double escape sequences) giving you a HTTP Error 404.11 – URL_DOUBLE_ESCAPED when downloading a book named as "Born to Run - Mercedes Lackey.epub"
The link would be 
`download/242/Born+to+Run+-+Mercedes+Lackey.epub`

See official info: Error message when you visit a Web site that is hosted on IIS 7.0: "HTTP Error 404.11 – URL_DOUBLE_ESCAPED" - https://support.microsoft.com/en-gb/kb/942076

I try to include the rule to allow URL_DOUBLE_ESCAPED in my web.config (I am on a shared host, no access to server level)
```
    <security>
      <requestFiltering allowDoubleEscaping="true" />
    </security>
```
But this caused the server to fire a "404 error not found" when downloading books

- To make it work again I had to change my config_local.php to disable URL rewriting

```
$config['cops_use_url_rewriting'] = "0";
```
So now it works... but
- accentuated characters are not used in file name but replaced by strange letters, 
- Kobo ereader can't download anymore

So this is a big mess!

Question is:
- How to really avoid the + signal in the URL and keep the URL rewriting on IIS 7 servers

Note that allowing Double escape sequences is a security issue:
Another IIS Blog - IIS7 rejecting URLs containing + - http://blogs.iis.net/thomad/iis7-rejecting-urls-containin

**Comment by horus68** [comment]
Update on file names, after disabling URL rewriting

A file uploaded as:
`Os dragoes nao conhecem o parai - Caio Fernando Abreu.epub`
and titled on Calibre with
`Os dragões não conhecem o paraíso`
from an author named
`Caio Fernando Abreu`
is now downloaded as
`Abreu, Caio Fernando - Os dragÃµes nÃ£o conhecem o paraÃ­so.epub`

Then again I had to edit the config_local.php to avoid updating metadata when downloading to 
`    $config['cops_update_epub-metadata'] = "0";`
and now files are downloaded with same name they had been uploaded. 

But what i wanted is to need to have URL rewriting and epub metadata update enabled on my library. Updating metadata on epubs when downloading files is a must have feature. 
I know that files could have been fine tuned in Calibre with the plugin to update metadata on epub files but it requires more work and sometimes we simple forget to use it and its not easy to use it.

But for now lets focus on how to change the URL rewright to not include to avoid '+' and use '%20' instead

**Comment by seblucas** [comment]
Hi, 

You've discovered two interesting problems. First one (url rewriting with IIS), it should be enough to modify the method `getHtmlLinkWithRewriting` in `data.php` to replace

```
        if ($config['cops_provide_kepub'] == "1" &&
            $this->isEpubValidOnKobo () &&
            preg_match("/Kobo/", $_SERVER['HTTP_USER_AGENT'])) {
            $href .= urlencode ($this->getUpdatedFilenameKepub ());
        } else {
            $href .= urlencode ($this->getFilename ());
        }
```
by

```
        if ($config['cops_provide_kepub'] == "1" &&
            $this->isEpubValidOnKobo () &&
            preg_match("/Kobo/", $_SERVER['HTTP_USER_AGENT'])) {
            $href .= urlencode (str_replace (" ", "%20", $this->getUpdatedFilenameKepub ()));
        } else {
            $href .= urlencode (str_replace (" ", "%20", $this->getFilename ()));
        }
```

I have yet to check for side effects but it should be fine.

**Comment by seblucas** [comment]
About your other problem, which browser are you using ?

**Comment by seblucas** [comment]
If you manage to test my previous change, don't bother to start a PR, there's a lot of unit test to change (I've already done it locally).

**Comment by seblucas** [comment]
Commit done 2bd02496fe64cf1d1ebbaa2f7ca2cc0b3afddf18

**Comment by horus68** [comment]
the solution is not working for me. Tested under Firefox and Chrome latest versions
The actual file can be read fine with epub preview or downloaded ok when URL rewrite is disabled
 http://bedigital.aegmmaia.pt/index.php?page=3&id=75
![2016-02-16 10_16_47-caio fernando abreu](https://cloud.githubusercontent.com/assets/3055443/13073963/8f4cc572-d499-11e5-9fb0-bcc5fa40a20f.png)

to implement your fix:
urlencode to rawurlencode data.php file:
```
        if ($config['cops_provide_kepub'] == "1" &&
            $this->isEpubValidOnKobo () &&
            preg_match("/Kobo/", $_SERVER['HTTP_USER_AGENT'])) {
            $href .= rawurlencode ($this->getUpdatedFilenameKepub ());
        } else {
            $href .= urlencode ($this->getFilename ());
        }
```
and  config_local.php goes like this
```
   $config['cops_use_url_rewriting'] = "1";
   $config['cops_provide_kepub'] = "1";
```
it fires a HTTP Error 404.11 - Not Found
and the URL is
http://bedigital.aegmmaia.pt/download/156/Os+dragoes+nao+conhecem+o+parai+-+Caio+Fernando+Abreu.epub

Requested URL	   http://bedigital.aegmmaia.pt:80/download/156/Os+dragoes+nao+conhecem+o+parai+-+Caio+Fernando+Abreu.epub
Physical Path	   C:\inetpub\wwwroot\download\156\Os+dragoes+nao+conhecem+o+parai+-+Caio+Fernando+Abreu.epub

![2016-02-16 10_51_01-iis 8 5 detailed error - 404 11 - not found](https://cloud.githubusercontent.com/assets/3055443/13074264/5e12bdf2-d49b-11e5-9e77-790a7761030e.png)

**Comment by seblucas** [comment]
Just to be sure did you replace both `urlencode` by `rawurlencode` ?

**Comment by horus68** [comment]
yes, double time confirmed!
Then it gave the error 404 described in the end of the last reply

**Comment by seblucas** [comment]
OK, I think I may have forgot to use my brain before coding ....

How did you configure IIS for the URL rewriting ? COPS installation package does nothing by itself ! IIRC I tried to configure it at work and I needed to install a specific package, I'll check if I can find it

**Comment by seblucas** [comment]
Hi, here is the web.config I tested : 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <staticContent>
            <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="14.00:00:00" />
        </staticContent>
        <rewrite>
            <rules>
                <rule name="Download with db" stopProcessing="true">
                    <match url="download/(\d*)/(\d*)/.*\.(.*?)$" />
                    <action type="Rewrite" url="fetch.php?data={R:1}&amp;db={R:2}&amp;type={R:3}" appendQueryString="false" />
                </rule>
                <rule name="Download without db" stopProcessing="true">
                    <match url="download/(\d*)/.*\.(.*?)$" />
                    <action type="Rewrite" url="fetch.php?data={R:1}&amp;type={R:2}" appendQueryString="false" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

**Comment by horus68** [comment]
With your fix for web.config download now works fine with URL rewrite.
Should we updated the wiki or will this fix be a standard in new version?

The second issue is still on ( strange letters if $config['cops_update_epub-metadata'] = "1"; ) but I will open a new issue to make this simpler to follow!

**Comment by seblucas** [comment]
Thanks for the confirmation (I've committed an updated web.config), I guess updating this [wiki page](https://github.com/seblucas/cops/wiki/Url-Rewriting-with-COPS) could help at least to confirm it's supported.
