### ISSUE TITLE
Kobo Glo ebook download doesn't work

### ISSUE THREAD

**Issue by huggenknubbel** [seblucas/cops#251]
if i press on the epub button the download doesn't start. i try it with the Calibre server and it is working.

**Comment by horus68** [comment]
Where are you tryng to download (URL)
Kobo Aura HD works fine on COPS libraries but the library needs to be fine tuned for Kobo devices:

Include your config_local.php file:

```
$config['cops_use_url_rewriting'] = "1";
$config['cops_provide_kepub'] = "1";
```

Note: those settings are explained in config_default.php comments

**Comment by seblucas** [comment]
Are you sure you enabled the URL rewriting ? This is MANDATORY for the kobo browser.

EDIT : horus beat me to it ;)

**Comment by seblucas** [comment]
there is more documentation here : https://github.com/seblucas/cops/wiki/Url-Rewriting-with-COPS

**Comment by horus68** [comment]
Seblucas: URL rewriting can't be used with IIS server (recent versions). See issue:
https://github.com/seblucas/cops/issues/249

**Comment by huggenknubbel** [comment]
thank you all. now it works.
i was confudes beceause on my laptop ist was working and not on my kobo. 
now i'm happy. 
Thanks a lot! :+1:
