### ISSUE TITLE
OPDS client tries to fetch the wrong URL

### ISSUE THREAD

**Issue by HiPPoNaX** [seblucas/cops#252]
I'm using COPS on Ubuntu Server 14.04 with apache2 (2.4.7) and php5 (5.5.9). The script is located at `http://<SERVER_IP>/cops`
`$config['cops_full_url'] = 'http://<SERVER_IP>/cops/';` is in `config_local.php`
Everything is okay from a desktop browser (HTML UI, downloading books, feed.php). However, if I try to access it from an OPDS client, strange things are happening: FBReader and Moon+ Reader are trying to access COPS at `http://<SERVER_IP>/...`, but the correct URL should be `http://<SERVER_IP>/cops/...` (Aldiko and Mantano are using the latter).

Relevant parts of the apache2 access log:
### FBReader
```
<PHONE_IP> - - [16/Feb/2016:22:53:41 +0100] "GET /favicon.ico HTTP/1.1" 404 501 "-" "FBReader/2.6.8 (Android 6.0.1, t03g, GT-N7100)"  
<PHONE_IP> - - [16/Feb/2016:22:56:56 +0100] "GET /images/author.png?v=1.0.0RC4 HTTP/1.1" 404 507 "-" "FBReader/2.6.8 (Android 6.0.1, t03g, GT-N7100)"
<PHONE_IP> - - [16/Feb/2016:22:57:10 +0100] "GET /feed.php?page=1 HTTP/1.1" 404 498 "-" "FBReader/2.6.8 (Android 6.0.1, t03g, GT-N7100)"
```

### Moon+ Reader
```
<PHONE_IP> - - [16/Feb/2016:23:00:22 +0100] "GET /cops HTTP/1.1" 301 568 "-" "Stanza iPhone/Aldiko/Moon+ Reader(Android)"
<PHONE_IP> - - [16/Feb/2016:23:00:22 +0100] "GET /cops/ HTTP/1.1" 302 246 "-" "Stanza iPhone/Aldiko/Moon+ Reader(Android)"
<PHONE_IP> - - [16/Feb/2016:23:00:22 +0100] "GET /cops/feed.php HTTP/1.1" 200 4199 "-" "Stanza iPhone/Aldiko/Moon+ Reader(Android)"
<PHONE_IP> - - [16/Feb/2016:23:00:22 +0100] "GET /feed.php?page=8 HTTP/1.1" 404 498 "-" ""
```

### Aldiko
```
<PHONE_IP> - - [16/Feb/2016:23:11:20 +0100] "GET /cops/feed.php HTTP/1.1" 200 1057 "-" "Mozilla/5.0 (Linux; Android 6.0.1; GT-N7100 Build/MMB29T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.71 Mobile Safari/537.36 Aldiko/3.0.23-standard"
<PHONE_IP> - - [16/Feb/2016:23:11:24 +0100] "GET /cops/feed.php?page=1 HTTP/1.1" 200 1064 "-" "Mozilla/5.0 (Linux; Android 6.0.1; GT-N7100 Build/MMB29T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.71 Mobile Safari/537.36 Aldiko/3.0.23-standard"
```

### Mantano
```
<PHONE_IP> - - [16/Feb/2016:23:13:18 +0100] "GET /cops/feed.php HTTP/1.1" 200 1057 "-" "Mozilla/5.0 (Linux; U; Android 6.0.1; en-us; GT-N7100 Build/MMB29T) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1 MantanoReader"
<PHONE_IP> - - [16/Feb/2016:23:13:21 +0100] "GET /cops/feed.php?page=1 HTTP/1.1" 200 1064 "-" "Mozilla/5.0 (Linux; U; Android 6.0.1; en-us; GT-N7100 Build/MMB29T) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1 MantanoReader"
```

I tried setting the OPDS URL in the client to `http://<SERVER_IP>/cops` or `http://<SERVER_IP>/cops/feed.php`, the same thing happens in both cases. Setting `$config['cops_generate_invalid_opds_stream']` to `0` or `1` also changes nothing. URL rewriting is off and I'm using the default `.htaccess` file.

Am I doing something wrong?

**Comment by seblucas** [comment]
Hi,

That's strange, `$config['cops_full_url'] ` is only used for the OPDS search (and in the OPDS link on the HTML) so it should not matter.

So what you're saying is that when you add an OPDS feed in FBReader with the url `http://<SERVER_IP>/cops/feed.php` it does not work ?

Do you have a proxy or reverse proxy ?

**Comment by HiPPoNaX** [comment]
Yes, because FBReader tries to fetch `http://<SERVER_IP>/feed.php` instead of `http://<SERVER_IP>/cops/feed.php`, which leads to 404 errors. FBReader does this from the beginning, but if you look at the logs, Moon+ Reader starts with the correct path, then (according to the 4th line) somehow gets redirected to `http://<SERVER_IP>/feed.php`
I'm not using any kind of proxy. It doesn't matter if I put COPS in the default DocumentRoot directory or elsewhere (with an alias in apache), the results are the same.

**Comment by seblucas** [comment]
Still strange ... :(

I'm only using subdomain with my production COPS so I have to admit, that's possible there's a problem here.

I'll deploy cops in a subdirectory and report back.

**Comment by seblucas** [comment]
Not reproduced, I've added this URL to my FB Reader : `http://192.168.43.171/cops/feed.php`

and it worked perfectly fine. Here are the relevant line of my IIS log (Sorry, I've no other webserver available for now, I'll try Nginx at home) : 

```
2016-02-17 16:37:41 192.168.43.171 GET /cops/feed.php - 80 - 192.168.43.159 FBReader/2.6.8+(Android+6.0.1,+hammerhead,+Nexus+5) - 200 0 0 854
2016-02-17 16:37:41 192.168.43.171 GET /cops/feed.php page=8 80 - 192.168.43.159 FBReader/2.6.8+(Android+6.0.1,+hammerhead,+Nexus+5) - 200 0 0 41
2016-02-17 16:37:53 192.168.43.171 GET /cops/feed.php - 80 - 192.168.43.159 FBReader/2.6.8+(Android+6.0.1,+hammerhead,+Nexus+5) - 200 0 0 57
2016-02-17 16:37:53 192.168.43.171 GET /cops/favicon.ico - 80 - 192.168.43.159 FBReader/2.6.8+(Android+6.0.1,+hammerhead,+Nexus+5) - 200 0 0 487
2016-02-17 16:37:57 192.168.43.171 GET /cops/feed.php db=0 80 - 192.168.43.159 FBReader/2.6.8+(Android+6.0.1,+hammerhead,+Nexus+5) - 200 0 0 64
```

**Comment by seblucas** [comment]
Did you try to remove completely `$config['cops_full_url']` ?

**Comment by HiPPoNaX** [comment]
Just did that, but got the same error unfortunately.

**Comment by seblucas** [comment]
I tested yesterday with Nginx at home and it still work fine.

Another idea, did you try to purge the cache of FBReader, maybe you entered the wrong url first (missing the `/cops/`) and it kept it in cache somehow.

Besides that I'm lost. I have no Apache available to test on but I'm pretty sure the problem lies elsewhere.

**Comment by thorindwarf** [comment]
I was struggling with this issue and Moon+ Reader Pro today.
Nothing helped until I added an extra slash at the end of the URL when adding new catalog, so it becomes `http://domain/cops/`
Without the slash Moon reader was giving me exactly the same error like in the issue described by HiPPoNaX.

**Comment by seblucas** [comment]
Indeed I remember seeing that in the early days of Moon+

**Comment by HiPPoNaX** [comment]
@thorindwarf : if COPS is configured to use an alias in Apache (instead of placing it directly in the DocumentRoot), then maybe the issue can be solved by modifying the Apache configuration.

If you set up your alias like this (with a trailing slash), then http://yourdomain.com/cops won't be aliased, only the files inside that subdirectory (eg. http://yourdomain.com/cops/feed.php):
`Alias /cops/ /var/www/cops/`

However if you remove the trailing slash, then http://yourdomain.com/cops will work as intended:
`Alias /cops /var/www/cops`

You can find a more detailed explanation about this in the [Apache documentation](https://httpd.apache.org/docs/2.4/mod/mod_alias.html#Alias)

URL rewriting works for me now with the latter setting. It's possible, that this caused the original issue for me too, however the disk containing that configuration have failed since then, so I can't check my original settings.

**Comment by thorindwarf** [comment]
@HiPPoNaX 
My configuration is Apache has ever been:
`Alias /cops          "L:/domain/cops"`
