### ISSUE TITLE
Wrong letters when downloading with updated metadata - IIS server

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#253]
On a IIS server 7 with URL Rewrite activated and with config_local.php
```
    $config['cops_update_epub-metadata'] = "0";
    $config['cops_use_url_rewriting'] = "1";
```

A file uploaded as:
`Os dragoes nao conhecem o parai - Caio Fernando Abreu.epub`
and titled on Calibre with
`Os dragões não conhecem o paraíso`
from an author named
`Caio Fernando Abreu`

is now downloaded as
`Abreu, Caio Fernando - Os dragÃµes nÃ£o conhecem o paraÃ­so.epub`

If config_local.php is configured to not update metadata when downloading:
`    $config['cops_update_epub-metadata'] = "0";`
files are downloaded with same name they had been uploaded but I they don't have the metadata updated. 

For me updating metadata for epubs, when downloading files, is a must have feature. It also solves the issue on name files (including PDF)
I know that files can be fine tuned in Calibre (with the plugin to mass update metadata on epub files) but sometimes we simple forget to use it. 

Note: URL rewrite was setup as discussed in
https://github.com/seblucas/cops/issues/249#issuecomment-184718297

**Comment by seblucas** [comment]
Did you try with many browser ? If yes, do all browsers have the same problem ?

Thanks in advance.

**Comment by horus68** [comment]
Tested under Win10 with Firefox, Crhome, Edge, Opera
You can text it now (I will leave the setup like this for a day): 
http://bedigital.aegmmaia.pt/index.php?page=3&id=75

Note: it happens on all other books from this library.

**Comment by seblucas** [comment]
OK, I've reproduced it. It seems that Portuguese diacritics are harder to handle than French diacritics (except for this single one : `œ` which mimic your problem). I'll try to fix it properly tonight. You can remove your link if you wish (don't need it anymore).

Thanks a lot for this report. I previously thought it was an Internet Explorer only problem.

**Comment by seblucas** [comment]
Another question, can you tell me the locale you're using in your browsers ? is it English or Portuguese ?

**Comment by horus68** [comment]
My locale is pt-PT

Same as COPS language:
`    $config['cops_language'] = 'pt_PT';`

**Comment by seblucas** [comment]
Thanks a lot.

**Comment by seblucas** [comment]
The bug was well hidden but I think I found it, I won't commit it for now as the problem lies in a dependencies but I'll leave you some instructions so you can test it.

You'd have to edit the function `OutputOpen` in `resources/php-epub-meta/tbszip.php` to change the big else block to make it like this : 

```
			} else {
				header ('Pragma: no-cache');
				if ($ContentType!='') header ('Content-Type: '.$ContentType);
				if (strlen($File) != strlen(utf8_decode($File))) {
					header('Content-Disposition: attachment; filename="book.epub"; filename*=utf-8\'\'' . rawurlencode($File));
				} else {
					header('Content-Disposition: attachment; filename="'.$File.'"');
				}
				header('Expires: 0');
				header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
				header('Cache-Control: public');
				header('Content-Description: File Transfer'); 
				header('Content-Transfer-Encoding: binary');
				$Len = $this->_EstimateNewArchSize();
				if ($Len!==false) header('Content-Length: '.$Len); 
			}
```

I've tested it with Chrome, Firefox, Edge. It should also work with IE11. I won't be able to test on my Kobo (on repair for the moment), so it will be great if you can ;) !

Thanks in advance.

**Comment by horus68** [comment]
Excellent work. It now works perfectly
Tested on windows browsers and Kobo AuraHD

Closing this and waiting for the 2.0 version so we can find more bugs and have fun sharing books!
