### ISSUE TITLE
Download of PDF not working (epub is working)

### ISSUE THREAD

**Issue by alex9434** [seblucas/cops#271]
When activating
    $config['cops_x_accel_redirect'] = "X-Accel-Redirect";
with NGINX PDF files cannot be downloaded. epub still continues to work.

There is no error message in error.log, but the error message from the browser is:
The webpage at https://example.com/cops/fetch.php?data=66&type=pdf&id=217&db=1 might be temporarily down or it may have moved permanently to a new web address.

**Comment by seblucas** [comment]
This should come from a configuration error on your end COPS demo use X-Accel-Redirect and it works :
http://cops-demo.slucas.fr/index.php?page=5&id=A
