### ISSUE TITLE
18 months since last release

### ISSUE THREAD

**Issue by doug-w** [seblucas/cops#273]
Hi Guys,

What do you think about merging in the custom calibre columns and cutting a 1.0.0 release?  We've been at RC3 since 12/2014...

**Comment by horus68** [comment]
+1 I think its relevant to release a final 1.0 version to reflect all the little changes already merged so it don't like a dead project.
Then create a new version to include new proposals available on actual PR

**Comment by seblucas** [comment]
Hi,

I know I'm a little (and certainly a little more than that) short on time lately. And there also was some big change proposed which were quite hard to review.

I'm waiting for several new or updated translations, I've merged what I could and will release the code for the rewrite in September.

In the meanwhile I'll release the awaited 1.0 next Saturday. I'll close the issue when it's done.

**Comment by horus68** [comment]
Great news. Please review this PR so I can send you refreshed translations too.
 Indentation change on master language by horus68 · Pull Request #255 · seblucas/cops - https://github.com/seblucas/cops/pull/255
