### ISSUE TITLE
[info] Translation updates

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#276]
There is a project to translate online in collaborative way using Transifex.
This allow users to translate without messing with code. It includes features as translation suggestion and memory translation. To translate you must join your language team (free). A team can have translators, reviewers and coordinators with ACL.

URL [https://www.transifex.com/projects/p/cops]
## Download

Any visitor can download language single files ready to use using web interface.
To download all languages in a single click you need to use the Client tool
## Updates
- Translators just need to translate using Transifex. 
- English file under Github is the master and automatically synchronized with Transifex
- Translations under Transifex are considered "work in progress" and should be taken as the "most recent translations"
- Translations under Github should be considered "translations deployed"
- Translations from Transifex will be included in Github by me or Seblucas

FAQ: why Transifex? No particular reason, by the time it was implemented it looked the best option.
It simply works fine with Transifex, no pre/post prepare of files required.
Note: I did not create a project under Crowdin or webtranslate-it but systems are similar (I'm a translator on both platforms)!

![2016-07-01 15_48_09-cops calibre server _ transifex editor](https://cloud.githubusercontent.com/assets/3055443/16525260/66ebd8f0-3fa3-11e6-95d3-572fd55db627.png)

See wiki: https://github.com/seblucas/cops/wiki/Update-translations

**Comment by horus68** [comment]
### Translators can download single file from the browser interface

### Advanced users - Help on using client tool
http://docs.transifex.com/client/setup/

You can use this config file for the Transifex tool
```
[main]
host = https://www.transifex.com
lang_map = en_GB: en, af_ZA: af, am_ET: am, ar_AA: ar, as_IN: as, ast_ES: ast, az_AZ: az, ba_RU: ba, be_BY: be, bg_BG: bg, bn_IN: bn, bo_CN: bo, br_FR: br, bs_BA: bs, ca_ES: ca, cs_CZ: cs, cy_GB: cy, da_DK: da, de_DE: de, dsb_DE: dsb, dv_MV: dv, el_GR: el, eo: eo, es_ES: es, et_EE: et, eu_ES: eu, fa_IR: fa, fi_FI: fi, fil: fil, fo_FO: fo, fr_FR: fr, fy_NL: fy, ga_IE: ga, gd: gd, gl_ES: gl, gu_IN: gu, ha: ha, he_IL: he, hi_IN: hi, hr_HR: hr, hsb: hsb, ht_HT: ht, hu_HU: hu, hy_AM: hy, id_ID: id, is_IS: is, it_IT: it, ja_JP: ja, ka_GE: ka, kk_KZ: kk, kl: kl, km_KH: km, kn_IN: kn, ko_KR: ko, ku_IQ: ku, ky: ky, lb: lb, lo_LA: lo, lt_LT: lt, lv_LV: lv, mi: mi, mk_MK: mk, ml_IN: ml, mn_MN: mn, mr_IN: mr, ms_MY: ms, mt_MT: mt, my_MM : my, nb_NO: nb, ne_NP: ne, nl_NL: nl, nn_NO: nn, nso: nso, oc: oc, or_IN: or, pa_IN: pa, pl_PL: pl, ps: ps-AF, pt_BR: pt_BR, pt_PT: pt_PT, ro_RO: ro, ru_RU: ru, rw: rw, sah: sah, sd: sd, se: se, si_LK: si, sk_SK: sk, sl_SI: sl, sma: sma, sq_AL: sq, sr_RS: sr, sv_SE: sv, sw_KE: sw, ta_IN: ta, te_IN: te, tet: tet, tg_TJ: tg, th_TH: th, tk_TM: tk, tl_PH: tl, tn: tn, tr_TR: tr, tt: tt, tzm: tzm, ug: ug, uk_UA: ua, ur_PK: ur, uz@Latn: uz, vi_VN: vi, wo_SN: wo, xh: xh, yo: yo, zh_CN: zh, zu_ZA: zu

minimum_perc = 1

[cops.localization_enjson]
file_filter = translations/cops/lang/Localization_<lang>.json
source_file = translations/cops/lang/Localization_en.json
source_lang = en_GB
type = KEYVALUEJSON
```

**Comment by seblucas** [comment]
I'll update the french language file with it and see how it goes. Could you do the same for Portuguese before I release the version ?

Thanks a lot

**Comment by horus68** [comment]
@seblucas all languages updated https://github.com/seblucas/cops/pull/278

**Comment by seblucas** [comment]
Great, I found one error fixed in https://github.com/seblucas/cops/commit/af15b6579982bee7e14da3e15f254f745f1f5235 could you update the Portuguese translation for `"customcolumn.stars.none"`, my guess is `Sem estrela` but beside `obrigado` and `Bom dia` I wouldn't trust in my Portuguese skills.

**Comment by seblucas** [comment]
@horus68 
I saw that you updated the string on Transifex, could make a PR ?

**Comment by horus68** [comment]
will do, please wait a couple of hours (need to use may personal computer)!

**Comment by seblucas** [comment]
Thanks ;)

**Comment by horus68** [comment]
Translations - Fix "no stars" · Pull Request #280 - https://github.com/seblucas/cops/pull/280

**Comment by seblucas** [comment]
@horus68 

Small question about notification coming from Transifex, Today at 10:14 I received an email with this content : 

```
Hi Sébastien Lucas,
The source content of the resource Localization_en.json of the project COPS (Calibre Server) has been updated. 
```

Is there a way to see what was changed and who did that ? So far I think only an administrator can change the main language file so it should be you but this notification is not very useful as is.

**Comment by horus68** [comment]
I also recieved the notification! 
The file is automatically updated from github to Transifex. The transifex API checks Github for updates. Was there any change on Github?
If there is no change it should not fire that notice. Probably it is not working properly if the notices happens when no changes are done on Github!
I can take the feature off! Probably will contact Transifex on issue.

**Comment by seblucas** [comment]
There were some commits on the repository but not on the file (see https://github.com/seblucas/cops/commits/master/lang/Localization_en.json) So I guess the Transifex API is bad.

**Comment by horus68** [comment]
Waiting to see if this happens again and then remove the feature.
On the update system itself, it works fine on other project (but different format file, don't know if this would be relevant)
