### ISSUE TITLE
getAttribute on a non-object epub.php on line 75

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#281]
I got this error (COPS v1) when trying to view one book using html viewer on browser.
This is only on this book, not on the others. The epub downloads fine.
See: http://rbebook.esy.es/index.php?page=3&id=5

`Fatal error: Call to a member function getAttribute() on a non-object in /public_html/resources/php-epub-meta/epub.php on line 75`

Line 75 for the /epub.php is
`        $tocid = $spine->getAttribute('toc');`

any ideas?

**Comment by marioscube** [comment]
EPUBreader, an epub reader plugin for Firefox said:

"The ePub-file is corrupted and can't be opened."

Sigil could not open the file either.

My conclusion: "epub is broken" (nothing to do with COPS, not that you implied it ;-)  )

**Comment by seblucas** [comment]
Exactly, you can also use the online validator : http://validator.idpf.org/
