### ISSUE TITLE
pas de couverture de livres dans mon catalogue opds à cause de mon certificat autosigné

### ISSUE THREAD

**Issue by jajaX** [seblucas/cops#282]
salut,

déjà je reprends mon commentaire sur la page du blog =>

> je viens de mettre à jour vers la version 1.0 qui fonctionne sans soucis, merci ;)
> 
> je peux voir mon catalogue opds et télécharger mes ebooks sur mon smartphone (ou mes tablettes) sous Android. Par contre, toujours impossible d'avoir les couvertures de mes ebooks. j'ai testé avec le lien de démo (pris sur cette page) et cela fonctionne.
> 
> pour info, j'utilise une connexion chiffrée en https avec un certificat que j'ai créé moi-même. j'ai été obligé d'importer mon certificat sur mes appareils Android pour avoir accès à ma bibliothèque. j'utilise Pocketbook Reader et, à l'occasion, Bookani Free (anciennement Mantano Reader Free). pas moyen d'avoir les couvertures sur les 2 !

pc portable sous Kubuntu 16:04
php : PHP 5.6.23-1

4 bibliothèques dans Calibre.
sur mon smartphone, j'ai importé mon certificat pour =>

- les applications/vpn
- wifi

j'utilise la protection par login/mot de passe.

une idée ?

**Comment by jajaX** [comment]
je viens de désactiver ma redirection https, pour test, les couvertures fonctionnent avec mon adresse 192.168.1.17/cops/feed.php. une fois remise, plus rien évidement...

donc c'est bien le https qui pose soucis !

**Comment by jajaX** [comment]
c'est bon ça fonctionne après une remise à plat avec la dernière version !

**Comment by jajaX** [comment]
près remise en place de la protection par mot de passe, ça refonctionne plus ! grrr

**Comment by seblucas** [comment]
I'll follow in French but english is preferred here ;)

Alors, c'est un problème lié au lecteur. Si tu utilise FBReader tu ne devrais pas avoir le moindre problème.

Le seul moyen que j'ai pu trouver est de désactiver le controle par mot de passe sur les images, je l'ai ajouté il y a quelques années : 
 * https://github.com/seblucas/cops/blob/master/.htaccess#L67-L82
 * https://github.com/seblucas/cops/blob/master/config_default.php#L281-L289

Le plus simple étant d'utiliser un client OPDS non buggé ;)

**Comment by jajaX** [comment]
effectivement, ça fonctionne avec FBReader mais je l'aime pas trop... c'est pas grave, j'ai viré la protection par mot de passe !

merci en tout cas ;)
