### ISSUE TITLE
Uninstalling COPS on Synology NAS

### ISSUE THREAD

**Issue by Lyox** [seblucas/cops#283]
I've been working for a Joomla based interface for my Calibre library. Now it's done and, after uninstalling COPS, I still got forwarded to a **checkconfig.php** when trying to access my NAS via _http://MY_NAS_IP/_.
How can I completely delete COPS from my NAS?

Synology NAS DS216J DSM 6.0

**Comment by seblucas** [comment]
I guess if the uninstall did not work you'll just have to delete the directory : 

https://github.com/SynoCommunity/spksrc/blob/master/spk/cops/src/installer.sh#L9-L11

that would be `/usr/local/cops` and maybe `/var/services/web/cops`

**Comment by Lyox** [comment]
The problem is that COPS was not installed in `/var/services/web/cops/` directory, but in `/var/services/web/` directly. Maybe, thats why it wasn't uninstalled properly.

The problem is solved:
I've removed all files manually thru SSH

**Comment by JCPvanHooren** [comment]
Hi Lyox,
I have the same issue; everything is in /var/services/web directly and am unable to restore WebStation to its default settings.
Which files did you remove to make it work again?
Please note that I'm a relative newbie; I have limited knowledge of any programming. I'm able to access and work out relevant tasks through SSH.
Thanks!
Joost

**Comment by Lyox** [comment]
Hi JCPvanHooren,
At first, it was my first experience with SSH & Putty and I was using [this](http://putty.eves.ru/) command list.
I've removed all apps with WebStation dependencies and, after that, I've removed all files from `/var/services/web/` listed in this repository and reinstalled all Apps again.
Unfortunatly, WebStation wasn't restored normally, so, on opening http://NAS_IP/ I have a permanent 403 error, but it's ok for me.
As an option, You can try to uninstall not only WebStation dependant apps, but remove a WebStation itself and then remove all contents of a `/var/services/web/` directory. 
Anyway, don't forget to backup all files, wich You about to remove.

**Comment by apexmbv** [comment]
just wanted to pop in here to say that the fix is to delete (or rename) the current /var/services/web directory then create a symbolic link in /var/services/ to your web station's "web" directory. For example:

rename the current /var/services/web directory:

     admin@XXXXX:~$ sudo mv /var/services/web /var/services/web-backup

create a symbolic link (soft) to your web station's root web directory (where "/volume2/web" is the location of my web station root directory)

     admin@XXXXX:~$ ln -s /volume2/web /var/services/web
