### ISSUE TITLE
Send by mail: special characters

### ISSUE THREAD

**Issue by Horla** [seblucas/cops#286]
Special by mail a book that got special characters resuts in some weird text in the subject of the mail.

Example:
"Bjørk" becomes "BjÃ¸rk" in the subject of the mail
"année zéro" becomes "annÃ©e zÃ©ro" in the subject of the mail

The body of the mail is fine.

**Comment by seblucas** [comment]
Can you replace this line : https://github.com/seblucas/cops/blob/master/sendtomail.php#L78 by

```
$mail->Subject =  utf8_encode('Sent by COPS : ' . $data->getUpdatedFilename ());
```

If it does not work can you try with `utf8_decode` ?
You can also try both while adding `$mail->CharSet = "UTF-8";` before setting the subject

**Comment by Horla** [comment]
It work with utf8_decode

**Comment by seblucas** [comment]
Can you also check with `$mail->CharSet = "UTF-8";` and without any other modification ?

Thanks in advance

**Comment by Horla** [comment]
With _$mail->CharSet = "UTF-8";_ it works too.
