### ISSUE TITLE
OPDS: downloading with koreader results in unreadable files

### ISSUE THREAD

**Issue by Horla** [seblucas/cops#287]
I am using koreader on a kobo touch n905. When I am using the OPDS feature with Feedbooks for example, it works great (epub, pdf). When I am using the OPDS feature with my personal COPS installation, I can browse through the categories. 

However, when I download a book, the files downloaded are unreadable by koreader and unreadable on my computer (pdf and epub). Did I miss something with the configuration of COPS?

**Comment by seblucas** [comment]
Can you check the end of your `config_local.php` and look for `?>` ?
Please remove it if you find it.

Did you check on real desktop browser ? Does it have the same problem ?

**Comment by Horla** [comment]
I checked `config_local.php`, there wasn't `?>`

I have tried my feed with firefox/lucifox and it worked fine.

**Comment by seblucas** [comment]
Ok can you compare the size on the downloaded epub between Firefox / Koreader.

Can you also try the download with Kobo's embedded browser

**Comment by Horla** [comment]
I don't have much luck with opds clients:
- Firefox: I didn't find how to download ebooks from it
- Kobo's embedded browser: it didn't recognize the feed (plain text)

Size of one ebook:
- with koreader (android): 35 ko (file isn't readable)
- with OPDS Browser (android): 366 ko (file is readable)

**Comment by seblucas** [comment]
I got the file you sent me ;)

If you rename your 35ko file from epub to jpg, you'll see a the book cover. So for an unknown reason Koreader download the cover and rename it with the epub name .....

The other file you sent was a zip, I assume you renamed it, it should have been an epub.

when I was talking about firefox or Kobo browser, I was thinking about using the HTML Catalog (index.php instead of feed.php)

**Comment by Horla** [comment]
The HTML catalog works fine with firefox/chrome. I will try with kobo's browser later.

About the zip file, I didn't rename it. It was like that when I downloaded with OPDS Browser.

Should I report this bug to koreader developers?

**Comment by seblucas** [comment]
You mean [OPDS Browser](https://play.google.com/store/apps/details?id=com.ynxsoft.opdsbrowser&hl=fr) ?
Did you try with FBReader (My favorite OPDS client and so fully tested) ?

I think that you can report the bug, I don't think the problem is on my end.

**Comment by seblucas** [comment]
Can you also try on my demo OPDS feed : http://cops-demo.slucas.fr/feed.php

If you have the same problem it will be easier for Koreader team to reproduce the problem

**Comment by Eduardomb22** [comment]
COPS is working fine using koreader at Kindle. I´ve tested the demo from the page and I can download and read the files.

**Comment by seblucas** [comment]
@Horla Can you do the test with the demo feed ?

**Comment by Horla** [comment]
I confirm that it works great with the demo feed. It seems like something is wrong with my installation.
