### ISSUE TITLE
Server side render problem with custom column

### ISSUE THREAD

**Issue by PaceyIV** [seblucas/cops#288]
In my  config_local.php I have declared some custom column:

`$config['cops_calibre_custom_column_list'] = array ("read", "pages");`

They are defined in the database as:

`1 | read | Letto | bool | 0 | 1 | {} | 0 | 0 |`
`4 | pages | Pagine | int | 0 | 1 | {"number_format": "{0:,}"} | 0 | 0 |`

On my Kindle Touch (4th generation) and on Google Chrome with server side render enabled on all device ( `$config['cops_server_side_render'] = "."`) I get the 500 error code:

`[Thu Aug 11 13:53:08.337531 2016] [:error] [pid 9746] [client 192.168.1.106:53728] PHP Fatal error:  Cannot use object of type CustomColumn as array in /media/data/ebooks/cops/resources/doT-php/doT.php(94) : runtime-created function on line 160, referer: http://192.168.1.1/ebooks/index.php?page=2&id=G&db=0
`

**Comment by slgray** [comment]
Some here with custom column and server side render.

```
2016/10/01 07:38:02 [error] 515#0: *125 FastCGI sent in stderr: 
"PHP message: PHP Fatal error:Cannot use object of type CustomColumn as array in 
/home/pi/cops/resources/doT-php/doT.php(94) :runtime-created function on line 160" 
while reading response header from upstream, client: x.x.x.x, server: , 
request: "GET /index.php?page=7&id=3 HTTP/1.1", upstream: 
"fastcgi://unix:/var/run/php5-fpm.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/index.php?page=7&id=3"
```

Here are checkconfig result form kindle:
![checkconfig](http://i.imgur.com/MDHdOLF.jpg)

**Comment by slgray** [comment]
I work around this issue by disable Server side render for Kindle 3. So far so good.

`$config['cops_server_side_render'] = "Kindle\/1\.0|Kindle\/2\.0|EBRD1101|EBRD1201|cybook";`

**Comment by seblucas** [comment]
@slgray 

is your Kindle still usable with client side rendering ? If yes, I'll remove it from config_default for the next revision.

**Comment by PaceyIV** [comment]
With client side rendering on Kindle Touch (User Agent Kindle/3.0+) there are too many redraws of the page, and the selected item blinks for a while.

**Comment by slgray** [comment]
@seblucas It still works great with `eink` theme. My device is Kindle Paperwhite (UserAgent: `"Mozilla/5.0 (X11; U; Linux armv7l like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+"`)
@PaceyIV maybe  you try  `eink` theme.

**Comment by PaceyIV** [comment]
I've tried eink them with client rendering and server side rendering: it works fine with both solution.
