### ISSUE TITLE
/icons directory interferes with default apache behaviour

### ISSUE THREAD

**Issue by cgxxx** [seblucas/cops#291]
As explained on this page : http://www.electrictoolbox.com/apache-icons-directory/ , the /icons/ directory at root level of your project interferes with apache and can't be overrided with htaccess if you don't control the full Apache server yourself

I suggest renaming it or moving into images/ directory, and correct templates in consequence :)

**Comment by seblucas** [comment]
Ok, can you make a PR ?

**Comment by cgxxx** [comment]
Okay, I'm brand new with github, so I need to figure how to do this first ^^
