### ISSUE TITLE
Audiobooks the exceed 120MB will not download.  Is there a way to increase this limit in my server?

### ISSUE THREAD

**Issue by alanjross** [seblucas/cops#297]

**Comment by Ecksters** [comment]
Seems like your PHP settings could potentially limit a download size(timeouts, etc.)

http://stackoverflow.com/questions/19509440/increase-the-limit-of-file-download-size-in-document-management-system

Of course it depends what server you're using.

**Comment by seblucas** [comment]
You have many options : 
 * First you can use a higher memory limit in your php.ini
 * You can also turn off `output_buffering`  in your php.ini 
 * My personal choice is to let your webserver do its job and configure this [param](https://github.com/seblucas/cops/blob/master/config_default.php#L65-L72)

I'm using `X-Accel-Redirect` and I downloaded a 1Go test file without any problem (that was many years ago, but I'm confident it still works).

**Comment by alanjross** [comment]
I thank both of you for your help.  It took me a while to figure out that my Synology server had 4 php.ini files in different locations, and they all had to be edited to effect the solution.  I used the all setting mods suggested in your stackoverflow.com link, and turned off output buffering.  I no longer get the http 500 error with larger downloads.  Thanks again!
Alan
__________________________
