### ISSUE TITLE
There is no option to send an ebook by email

### ISSUE THREAD

**Issue by kevinverelst** [seblucas/cops#299]
In the settings, a user can fill in an email address on which they want the receive the ebook but there is no option in the view to actually send it?

**Comment by seblucas** [comment]
Yes there is ;)

You have to go to the book detail (like in this [url](http://cops-demo.slucas.fr/index.php?page=13&id=17&db=)) and configure your [smtp server](https://github.com/seblucas/cops/blob/master/config_default.php#L212-L233).

I'll let you close the ticket yourself once you made it work.

**Comment by kevinverelst** [comment]
Thx for your quick response, i'll try it out and let you know

**Comment by kevinverelst** [comment]
I think i'm doing something wrong because i can't get it to display the email icon.
My config looks like this (with filled in credentials off course):

```
<?php
    if (!isset($config))
        $config = array();

    /*
     * The directory containing calibre's metadata.db file, with sub-directories
     * containing all the formats.
     * BEWARE : it has to end with a /
     */
    $config['calibre_directory'] = '/volume1/calibre/';

    /*
     * Catalog's title
     */
    $config['cops_title_default'] = "@cops_title@";

    /*
     * use URL rewriting for downloading of ebook in HTML catalog
     * See README for more information
     *  1 : enable
     *  0 : disable
     */
    $config['cops_use_url_rewriting'] = "@use_url_rewriting@";

	$config['cops_mail_configuration'] = array("smtp.host" => "smtp.gmail.com",
												"smtp.username" => "",
												"smtp.password" => "",
												"smtp.secure"=>"ssl",
												"address.from"=>"");
    ?>
```

**Comment by CHBMB** [comment]
AFAIK only works with mobi books.  Icon doesn't appear for epub

**Comment by kevinverelst** [comment]
Yeah, i'm working with mobi files

**Comment by seblucas** [comment]
@CHBMB 

That's not entirely true it will send the most interesting format in the following list (on the left : less interesting, on the right : more interesting) : array ("EPUB", "PDF", "AZW3", "MOBI"); (see [here](https://github.com/seblucas/cops/blob/master/book.php#L273-L286))

@kevinverelst 

That strange, if you know a little PHP, the logic is [here](https://github.com/seblucas/cops/blob/59bcaba7f3e4702aa2a31bdafa4aeee48fe870a6/JSON_renderer.php#L87-L89) so if you have $config['cops_mail_configuration'] filled and a mobi file in your book detail that should work fine.

**Comment by kevinverelst** [comment]
Fixed it, i was modifying the wrong config file, my bad.

**Comment by CHBMB** [comment]
@seblucas I never knew that.  I always convert my books to mobi to use the email feature, looks like I might have been wasting my time, has this always been the case?  If so I feel a right idiot!

**Comment by horus68** [comment]
Thanks @seblucas the stuff we can learn from your replies...
I always edited the most interesting format from left (best) to right (worst). 
And now I found I was just making it wrong, so I'm also on the same boat then @CHBMB

**Comment by seblucas** [comment]
@CHBMB 

First a disclaimer, I honestly don't want to make anybody feel like an idiot ;)
It wasn't here from the start but still since 21 Jun 2013 : https://github.com/seblucas/cops/commit/e833172e9981472d9f6cdcc1be307d7013eb38eb

I added it mainly for myself : I have no Mobi / AZW3 (only EPUB, PDF) but I still need to send a book by email sometimes.

@horus68 

I admit it may need some comments to make it crystal clear ;)
