### ISSUE TITLE
Wrong content type

### ISSUE THREAD

**Issue by alex9434** [seblucas/cops#300]
Dear all,

Thank you for your great program. I have an issue when using COPS with Cool Reader. I use Ubuntu with PHP 5.6 and Apache2. When I try to access the directory http://example.com/cops/feed.php, I get the following message:
Cannot parse ODPS catalog: unexpected content type application/xml
When I try to access the page http://example.com/cops/feed.php with the browser, I get the following error: 
This page contains the following errors:
error on line 4 at column 12: Encoding error
Below is a rendering of the page up to the first error.

Open Publication Distribution System Unofficial Validator provides the following message:
Validation Failed
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.

Apache2 does not show anything in the error log. What could I do wrong? Any tipps?

**Comment by alex9434** [comment]
Just wanted to add that the web-interface on http://example.com/cops/ works flawlessly. I only changed the .htaccess file to activate basic auth.

**Comment by seblucas** [comment]
Without sharing your server url, could you share the feed content. I won't be able to help without that
