### ISSUE TITLE
_CLEAR_ button for tag filtering requires text for users

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#304]
When using search with activated navigation filter for tags,  the text  `_CLEAR_` shows up as a button to allow clear tag filtering.
![2016-11-21 14_36_28-recent additions](https://cloud.githubusercontent.com/assets/3055443/20486726/c9a44318-aff8-11e6-85a0-d0617bef06ec.png)
or
![2016-11-21 14_43_13-adicionados recentemente](https://cloud.githubusercontent.com/assets/3055443/20486757/ea2e3bc0-aff8-11e6-82f6-d69d5c19bed9.png)

This doesn't look good to me. Also it should be a translatable text!

Side question: is it possible to have tag filtering as an option for local config file, not only by user setting?

**Comment by horus68** [comment]
this involves the file \util.js
line 201
`    $("#filter ul").append ("<li>_CLEAR_</li>");
`
line 256
```
function handleFilterEvents () {
    $("#filter ul").on ("click", "li", function(){
        var filter = $(this).text ();
        if (filter === "_CLEAR_") {
            filterList = {};
            $("#filter ul li").removeClass ("filter-exclude");
            $("#filter ul li").removeClass ("filter-include");
            doFilter ();
            return;
        }

```
Now the question is: how to make this into a language variable so its possible to translate?
@seblucas

**Comment by seblucas** [comment]
@horus68 should be fixed, could you update Transifex with the new translation string : "filter.clearall' I think I forgot how to do that.

I guess that the translation maybe automatic for many languages (as Clear All should be used in other projects). As usual I can do french and italian if Transifex cannot do that automatically.

**Comment by horus68** [comment]
@seblucas Transifex source updated now.
Will wait until 24 june to make a PR with the new translations so translators can have some time to translate!

**Comment by seblucas** [comment]
Great, in any case I'll make a release tomorrow as starting friday, I'll be away for a two week work trip in Africa and I won't have time to work on COPS.

**Comment by horus68** [comment]
@seblucas I have added a PR for translations (and another for icons).
Hope you find the time to include them in the new release so its easier for all to download and use.

Have a safe return!
