### ISSUE TITLE
Access Error on Android Apps

### ISSUE THREAD

**Issue by dom-madrid** [seblucas/cops#306]
Hi,
I am using COPS in various setups. The html/php part works without problem (since way before the current version). Today I installed the latest version 1.01, and added basic security through Apache.
It works via web, it works on Ipad with Stanza, but on Andoid, although the setup process goes through correctly, there is no way to access the library. On android Marshmallow with either Fbreader or Moon+ Reader, the catalog is not loaded. Moon+ gives a little more info:
My setup is as follow  www.mydomain.com/apps/cops
Moon+ say it cannot find www.mydomain/apps/feed.php
It seems to me it is not looking in the right directory, but one level up...
In prior version and without security, it used to work everywhere.
Any ideas? Is it a cops problem? Or a cops/android problem?
Thanks for any ideas.

**Comment by CHBMB** [comment]
Have you tried `www.mydomain.com/apps/cops/`

**Comment by horus68** [comment]
There is a similar issue (no real solution besides clearing cache)
https://github.com/seblucas/cops/issues/252
Also: make sure if no security allows Moon+ to access the correct URL

**Comment by seblucas** [comment]
I can confirm that FBReader on Android work perfectly with a password protected COPS. You just have to know that it heavily cache almost everything so sometimes it's better to change url : 

www.mydomain.com/apps/cops -> www.mydomain.com/apps/cops-try2
