### ISSUE TITLE
When using HTTPS, mixed content on login.html

### ISSUE THREAD

**Issue by FesterHead** [seblucas/cops#307]
When using HTTPS the request for fonts from Google results in a mixed content warning block.

Fix:  remove the "http:" from the URL.
`<link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=Open+Sans:400,300italic,800,300,400italic,600,600italic,700,700italic,800italic' />`

This will result in either an HTTP request from HTTP sites or an HTTPS request fot HTTPS sites.

Alternatively, change the URL to only use HTTPS.
`<link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,800,300,400italic,600,600italic,700,700italic,800italic' />`

**Comment by polytan02** [comment]
I created a pull request for this 👍 
https://github.com/seblucas/cops/pull/308

**Comment by polytan02** [comment]
Should this be closed now ?

**Comment by seblucas** [comment]
Will you remake your pull request based on my comment https://github.com/seblucas/cops/pull/308#issuecomment-266879740 ?

If not I'll do it tonight, I just don't want two people doing the job, it's always frustrating ;)

**Comment by polytan02** [comment]
Thanks @seblucas , your commit looks much better than mine :)
