### ISSUE TITLE
Rethink the indexing.

### ISSUE THREAD

**Issue by dsbrooks** [seblucas/cops#311]
I think removing the alphabet pages(A-Z) would be a much smoother experience. 

It's a pain to have to click 4 times(Authors -> B -> Ballard -> EPUB) to get to a book I want. This isn't the best UX. I think users expect a list of names, not a bunch of letters. 

For people who are looking at my library for the first time, they don't know what they are looking for always and might light to browse instead of A... back. B... back. C... back.

**Comment by Ecksters** [comment]
I agree and think there should be a full library listing, probably as the default when you visit the page.

**Comment by seblucas** [comment]
I agree, just so you know there are configuration items to remove the alphabet pages : 

https://github.com/seblucas/cops/blob/master/config_default.php#L135-L147

**Comment by dsbrooks** [comment]
I noticed the settings afterwards, but maybe set them to 0 as default? It would also work to put a toggle in the settings, maybe.

**Comment by seblucas** [comment]
On a side note, I feel that the user experience for ereaders, tablets or computer is completely different so it's hard to make one interface that make everyone happy.

On my Kobo's browser, scrolling is a pain so having alphabet pages is more that great. Using the virtual keyboard for a search is not that great.

On my tablet / phone, scrolling is great / fast, virtual keyboard is usable. So alphabet page can be great but are not mandatory.

On a real computer, I only use search, I almost never use any list.

My personal Calibre library has ~ 600 books so not small but certainly not as large as some COPS users (some thousand books)

**Comment by Northguy** [comment]
+1 for seblucas ... On a Kobo with a larger database it is a pain to find books without the alphabet pages. I think he summarised the different use cases between Kobo / tablet and PC perfectly.

**Comment by seblucas** [comment]
@Northguy 

Thanks for the +1, feels good to know my experience is not only mine ;). efficient UX is always hard to get right.
Also thanks for the wiki update.

Merry Xmas

**Comment by Northguy** [comment]
No problems... I moved my database and ran into the problem as now described in the Wiki :-) I hope to spare others the research I needed to do before I figured out the issue.

Regarding the rendering of COPS on a Kobo  device I would even advocate the addition of more buttons ;-)

- 10 books per page
- Flip forward / flip backward button (swiping is a bitch)
- Subdivide the Author and Title pages in yet another level:  AA - AD ; AD - AG; ..... AW - AZ based on the number of books in a category divided by x categories....;-)

But I guess that this a) would infuriate some people even further b) cost you your Christmas holidays... so nevermind :-p

Merry Xmas and a happy newyear to you too

**Comment by seblucas** [comment]
Hi

To enhance my user experience with COPS on Kobo, I use this patch : 

```
diff --git a/base.php b/base.php
--- a/base.php
+++ b/base.php
@@ -75,6 +75,14 @@
 function getCurrentOption($option)
 {
     global $config;
+    if (preg_match('/Kobo/', $_SERVER['HTTP_USER_AGENT'])) {
+        if ($option === 'max_item_per_page') {
+            return 7;
+        }
+        if ($option === 'template') {
+            return 'base';
+        }
+    }
     if (isset($_COOKIE[$option])) {
         if (isset($config ['cops_' . $option]) && is_array ($config ['cops_' . $option])) {
             return explode (',', $_COOKIE[$option]);

```

The cookies created by should last one year but they are removed by Kobo's browser, so this dirty hack allow me to always have the same settings for my Kobo (Aura HD for me).
I only show 7 books so that I never scroll.

That work great but I can't commit it as is. I would be quite hard to find a clean way to do that.

I thought of subdividing Author and Title pages but got bored after thinking of all kinds of side effects :(.

**Comment by seblucas** [comment]
I don't think I'll do this change. I may change my opinion if I see a PR but I doubt it. Sorry.
