### ISSUE TITLE
Document config_local.php.example with ALL the options/parameters

### ISSUE THREAD

**Issue by polytan02** [seblucas/cops#312]
Hi,

It would be appreciated to have all the configuration options listed in config_local.php.example so that we would know what can be tweeked and we would avoid typos or misuse.

Currently only 3 options are listed and then we need to browse the Web to know about https, login access, default template and many other things which I'm sure can be done but we don't know about :)

**Comment by horus68** [comment]
config_local.php.example has just the minimum options required to have an instance running with your name and declare the path to the folder with ebooks (default is none but you need to declare it see any book). 
This files simple override the COPS default options. You can add more options if you want to change the default behaviour.
All the options are in the file config_default.php

Note: you shouldn't change the options in the config_default.php to be upgrade safe. simple copy any option you want to change and place it in your personal file: config_local.php

**Comment by seblucas** [comment]
I hope this commit make things clearer

**Comment by polytan02** [comment]
That's perfect, thanks.
I have to say I did not notice config_default.php. This file is well done and all the options are listed ! :)
