### ISSUE TITLE
COPS is broken / PHP error

### ISSUE THREAD

**Issue by marioscube** [seblucas/cops#313]
The current (december 22nd) github version of COPS is broken.

On a Debian Jessie server with Apache 2.4 and PHP 5.6 (latest versions from the repositories) COPS does not start / react:
 - browser screen remains white
 - Apache PHP error log:
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/cops-dec/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/cops-dec/config.php on line 9
 --> directory ./vendor does not exist
 - removing the offending line in config.php leads to other errors, so that seems not  to be a quick solution. 

An older version of COPS (git cloned november 9th) works without any error message.

**Comment by seblucas** [comment]
You're right, I forgot to update the README.md with the new documentation. I'll do that this morning.

**Comment by seblucas** [comment]
Done, see https://github.com/seblucas/cops/blob/master/README.md#install-from-sources

Please tell me if that work ... (let's hope so) and if you think this can be better explained.

**Comment by Bonbadil** [comment]
I've updated some days ago and to make it work I used:
```bash
git pull
./composer-dl.sh
./composer.phar install
```
If I test your last line of instruction `php composer.phar --no-dev --optimize-autoloader`, I only get the help of composer because there is no command.

**Comment by seblucas** [comment]
you're right of course (failed copy/paste for the win ;))

**Comment by Bonbadil** [comment]
`php composer.phar install --no-dev --optimize-autoloader` worked great and removed a lot of dependency. Thank you.

**Comment by seblucas** [comment]
Fixed see https://github.com/seblucas/cops/commit/b13dbf064909c2d2c0802680b613ab16cb5722e8

@Bonbadil 
Thanks for the report.

**Comment by marioscube** [comment]
Using "b13dbf8" COPS again works fine!

I have just one remark: You just ruined the "one stop shop" concept of COPS (download, configure and it worx!). 
How to explain to semi-computer-illiterate users that they have to install composer (inside the COPS directory) for COPS to work. 
Previously I could just copy (even a  pre-configured) COPS to a web directory on a Synology, then copy some Calibre libraries into COPS on the Synology and it worked. And now ....... composer? ..... ssh? ...... wget ..... never mind.

Don't get me wrong, I still love COPS, but installing it just got 100% more difficult for the casual user (not for guys like you and me, for those geeks it's a challenge!) ;-)

**Comment by seblucas** [comment]
@marioscube 

I knew you would say that ;) and I thought about it too (especially when I had to update all my installed COPS)
That's why I also changed the Install part of the README (https://github.com/seblucas/cops/blob/master/README.md#install) to point to the release page where all packages (cops-X.X.X.zip) will always be completely self contained (no need for composer at all).

I'll maybe change the title to `Install a release (Easiest way)`, what do you think of that ?

**Comment by marioscube** [comment]
That solves 99.9% of my "problem".

Maybe the nginx reference needs a sub-head to not confuse Apache and other webserver (Synology / QNAP) users?

//off topic: thank you for updating COPS Classic! I feared you would devote your spare time to COPS 2.0? (But I still like the classic interface the best.)

**Comment by horus68** [comment]
> I'll maybe change the title to Install a release (Easiest way), what do you think of that ?

Agree on that. A self contained Cops is the natural option for a so beautiful application. I love the fact to not have to do more then unzip to a directory and work.
I always use a demo folder for books on your sip package when sending it to people that I help to have a digital library online.
Maybe an official release should also include 5 books as demo, so people can see COPS work from the first browser refresh!
Then they would configure and upload their book folder.
Note: you also need to have new release number, latest is from October!

**Comment by seblucas** [comment]
@marioscube 

I updated the README.md.
About your off-topic. My free time is very very limited for now so it has to be very usefull so mostly on COPS 1.0 for now. COPS 2.0 will need a lot of some love (and time) to overcome COPS 1.0 but that will come eventually.

@horus68 

The new release will certainly be next year ;).
I like the idea of a demo folder (and public domain ebooks, or better Creative Commons licensed ebooks to be sure I don't receive yet another letter from an angry editor/lawyer). What I don't like is to advertise the fact to store your Calibre library in the web directory, so we'll have to come up with an howto / link to a proper documentation. But indeed a very good idea and way better than to scare users with `Database error`.

@all

Merry Xmas to you !!!!

**Comment by BreizhCat** [comment]
Hi all !

Really happy to have part of the solution. I'm working on synology. 
@seblucas to use composer.phar we need to have phar extension enabled in php (webstation) and to add /root/ in open_basedir. I don't know why but it seems that installer use $HOME variable.

Merry Xmas too

**Comment by marioscube** [comment]
I haven't tried to install the "new" COPS with composer on Synology yet, but I might try next week.

Warning SECURITY risk!
It is my understanding that you should NEVER put /root in open_basedir if you plan to open access to your Synology to the internet. If you only plan to use the Synology on your own LAN, then who cares? 

Merry Xmas to all

**Comment by horus68** [comment]
@seblucas For the new version I was meaning new RELEASE for the actual 1.0 version :)
The latest self contained release is 1.01 (15 Oct 2016)
https://github.com/seblucas/cops/releases

Then again the base.php states 1.0.2
https://github.com/seblucas/cops/blob/master/base.php#L11

But with the merges from this month I think its required to have a new self contained release as a 1.1.0
(one number up because there has many changes in code (EOL) and Composer

**Comment by BreizhCat** [comment]
@marioscube Yes i'm aware of this kind of warning security. So I just added /root for the time of installing and i deleted it just after !

Thanks :) & merry xmas

**Comment by marioscube** [comment]
Just installed a new instance of COPS on my "new" Raspberry Pi 3 .... and it worked. 

(4 cores is nice for rendering covers server-side!)
