### ISSUE TITLE
Fix for koreader

### ISSUE THREAD

**Issue by leolivier** [seblucas/cops#315]
Hi,
Had a bug using cops with [koreader](https://github.com/koreader/koreader)
Fixed it by adding:
`if ($qid == null) $qid=getURLParam ("amp;id"); 
`
at line 25 in feed.php
Sorry, I can't tell you anymore what the bug was as I uninstalled koreader a while ago. I re discovered this fix when doing a diff between my version (based on 1.0.0RC4) and the 1.0.1 version to see what had changed.

**Comment by seblucas** [comment]
Hi

Your fix feels weird, it would mean that Koreader does not `urldecode` the URL coming from the OPDS feed. That would be strange (= a big problem in Koreader OPDS client code).

When did you last saw this bug ?

**Comment by leolivier** [comment]
Hi Seb
I fixée this un July, I think. Sorry I didn't créateur an issue for this on github attention that time...
But indeed, koreader dis not work with opds without that fix...

**Comment by seblucas** [comment]
Thanks, I'll test.

Offtopic : French auto complete in English is a PITA :(

**Comment by seblucas** [comment]
@leolivier 

This should be a bug in Koreader, let's see what they say about it.

**Comment by leolivier** [comment]
Great ! 
Offtopic: sorry for the auto complète, yes, a real PITA :) I'll disable it one day

**Comment by seblucas** [comment]
Seems fixed by [this commit](https://github.com/koreader/koreader/commit/392d43b12dbc222494299234209b7462cfc8df7f)
