### ISSUE TITLE
Authentication using config_local.username.php

### ISSUE THREAD

**Issue by DarkSir23** [seblucas/cops#316]
Since upgrading to 1.0.2 (from 1.0.0), I don't seem to be able to do user authentication using cops_basic_authentication

What appears to be happening it seems to be reading the config_local.user.php file once, but then a second time not doing so, because it doesn't carry the PHP_AUTH_USER when it loads config a second time, and pulls in the blank cops_basic_authentication config array.  I tested this by putting a default array in with bogus username and password, and then just above the check for username and password, dumping the contents of cops_basic_authentication.  It shows in succession, the contents of the array in my custom user config file, and then the contents of the default one.

Any idea what might have changed since 1.0.0?  I don't see anything unusual in config.php

Thanks,

**Comment by seblucas** [comment]
Hi,

1.0.2 is still under development and there were some heavy changes. I think what you're seeing is a regression.

Can you update to 1.0.1 and confirm it work fine ?

I'll check your problem.

**Comment by DarkSir23** [comment]
I went ahead and got it working with htpasswd.  Using the php password method was a relic from when I was running it on windows.  When I get home tonight, I'll set up a copy with 1.0.1

**Comment by marioscube** [comment]
I tried: 
  $config['cops_basic_authentication'] = array("username" => "user", "password" => "cops");
And I had no problems. It worked as expected.

Cops 1.0.2
PHP 5.6
Apache 2.4 webserver
Debian Jessie

**Comment by marioscube** [comment]
Just the line in config_local.php. No other method of authentication used (like .htaccess)

**Comment by seblucas** [comment]
I tried with this line in `config_local.php` : 
```
$config['cops_basic_authentication'] = array( "username" => "toto", "password" => "toto");
```

and with `config_local.toto.php` containing only a redefinition of `$config['calibre_directory']` and it works fine

My `config_local.php` has 7 databases and `config_local.toto.php` has only one => I see one database.

**Comment by marioscube** [comment]
Just for my information and education, why use "config_local.toto.php"?
What does it do? Did I miss something? (Hate that! ;-) )

**Comment by seblucas** [comment]
<offtopic>
If you enable authentication (with .htaccess for example), you can create as many files named "config_local.<username>.php" as you have user. These files can have the same configuration items as normal `config_local.php`.
My personal use is like that : 
 * My main `config_local.php` has 3 databases (books, women's books, kid books)
 * My wife has a special `config_local.wifeName.php` with a difference `$config['calibre_directory']` having only women's books. That way she only see her books
 * Later when my daughter will read, I'll create special files so that they only see Kids books. I could also forbid them to mail books that way.
</offtopic>

**Comment by seblucas** [comment]
it's explained here : https://github.com/seblucas/cops/wiki/User-based-config

**Comment by marioscube** [comment]
I did not know that. Thank you for explaining.

And then I thought I had read the wiki carefully (some time ago).

**Comment by DarkSir23** [comment]
I'll try it with 1.0.1 when I get home.  For authentication, htpassword is definitely the way to go, but it wasn't an option back in the pre-1.0 days (When I was still doing things in windows).  Much easier to wrangle on FreeBSD.

**Comment by seblucas** [comment]
Closing you can reopen it if you have new information.
