### ISSUE TITLE
Modifier le tri de la colonne RATING

### ISSUE THREAD

**Issue by JeanClaudeS** [seblucas/cops#320]
Quelqu'un sait-il ou peut-on modifier l'affichage de la liste des étoiles (rating) qui apparait dans l'ordre alphabétique, j'aimerai l'avoir dans l'ordre de la date d'inscription dans la bibliothèque.
Merci d'avance.
_Does anyone know or can you change the display of the star rating (which appears in alphabetical order), I would like to have it in order of the date of inscription in the library .
best regards_.

**Comment by horus68** [comment]
I can see those stars on the recently added tab : http://rbebook.esy.es/index.php?page=10
Is not the same in your library?

**Comment by seblucas** [comment]
As @horus68 said if you go to the recent books the default sort is by book's timestamp 👍 

https://github.com/seblucas/cops/blob/master/lib/Book.php#L56-L57

But I have to admit I don't really understand what you mean by star rating / timestamp order could you explain it a little more.

@horus68 
I removed your link as it seems to show copyrighted books

**Comment by horus68** [comment]
@seblucas No it has not, I only use books without copyright and books released by authors/editors as free contents (those are only to be shared, no reedits allowed)!

**Comment by seblucas** [comment]
My bad I've reverted my edit. Sorry for that.

**Comment by horus68** [comment]
no problem, this was just an example to understand what was the question on stars ordering.

**Comment by JeanClaudeS** [comment]
@seblucas 
Ce que je voulais c'est que l'item "appéciation" correspondant à "notes" dans Calibre s'affiche dans l'ordre chronologique : les plus récents d'abord. 
merci d'avance
_What I wanted is that the item "Appréciation" corresponding to "Notes" in _Calibre_ appears in chronological order: the most recent first._

**Comment by seblucas** [comment]
The order used is the following : 

https://github.com/seblucas/cops/blob/master/lib/Book.php#L58-L59

So it should not be chronological but based on book's title.
