### ISSUE TITLE
Unable to access database?

### ISSUE THREAD

**Issue by develroo** [seblucas/cops#321]
Hi,

I have tried the simple install of using the php inbuilt webserver but I get this

``php -S 192.168.0.106:8080
PHP 7.0.14-2 Development Server started at Mon Jan 23 10:53:20 2017
Listening on http://192.168.0.106:8080
Document root is /var/www/html/cops
Press Ctrl-C to quit.
[Mon Jan 23 10:53:23 2017] 192.168.0.150:47468 [302]: /
[Mon Jan 23 10:53:23 2017] PHP Fatal error:  Uncaught Exception: Database <> not found. in /var/www/html/cops/base.php:1257
Stack trace:
#0 /var/www/html/cops/base.php(1272): Base::error(NULL)
#1 /var/www/html/cops/base.php(1295): Base::getDb(NULL)
#2 /var/www/html/cops/base.php(1302): Base::executeQuerySingle('select count(*)...')
#3 /var/www/html/cops/author.php(43): Base::getCountGeneric('authors', 'cops:authors', '1')
#4 /var/www/html/cops/base.php(613): Author::getCount()
#5 /var/www/html/cops/feed.php(41): Page->InitializeContent()
#6 {main}
  thrown in /var/www/html/cops/base.php on line 1257
[Mon Jan 23 10:53:23 2017] 192.168.0.150:60158 [302]: /feed.php - Uncaught Exception: Database <> not found. in /var/www/html/cops/base.php:1257
Stack trace:
#0 /var/www/html/cops/base.php(1272): Base::error(NULL)
#1 /var/www/html/cops/base.php(1295): Base::getDb(NULL)
#2 /var/www/html/cops/base.php(1302): Base::executeQuerySingle('select count(*)...')
#3 /var/www/html/cops/author.php(43): Base::getCountGeneric('authors', 'cops:authors', '1')
#4 /var/www/html/cops/base.php(613): Author::getCount()
#5 /var/www/html/cops/feed.php(41): Page->InitializeContent()
#6 {main}
  thrown in /var/www/html/cops/base.php on line 1257
[Mon Jan 23 10:53:23 2017] 192.168.0.150:56216 [200]: /checkconfig.php?err=1
`

I have symlinked my Calibre dir with it's metadata.db in it to library but still get this error. it might be nice to echo the database path that is missing so I know it is trying to look in the right place?

I am using calibre v2.71 and cops v1.0.1

Any ideas?

Thanks.

**Comment by develroo** [comment]
Ok scratch that issue. php-sqlite3 was not installed. My bad.

Can connect to it now with FBreader on my phone. Cool

Thanks.

**Comment by horus68** [comment]
@develroo can you please close this issue?
