### ISSUE TITLE
fournir personnalisation de l'accès pour utiliser COPS comme une bibliothèque commune

### ISSUE THREAD

**Issue by hugoheitz** [seblucas/cops#324]
j'imagine ici utiliser COPS d'une manière un peu différente d'un usage classique.

usage classique : depuis mon device personnel (smartphone, tablette ou liseuse), j'accède à COPS qui présente la bibliothèque et je choisis de télécharger ou envoyer vers une liseuse le livre retenu.

usage cible : j'affiche sur un grand écran (une TV LED) avec un raspberry et un navigateur web la bibliothèque familiale ou collective. je m'authentifie et ceci personnalise alors le contexte pour savoir vers où envoyer le contenu.

possibilité de s'authentifier et faire évoluer en fonction les éléments concernant le send to.
pour simplifier 
construction d'une page particulière sur laquelle le système se logge par défaut (par exemple : library.php)
sur cette page, présentation des différents utilisateurs pouvant exister

exemple concret 
accès sur la page
je choisis l'utilisateur "Jean"
je peux me promener dans la bibliothèque et choisir un livre
lorsque je clique sur "envoyer sur la liseuse", c'est la liseuse de Jean qui est ciblée.

possibilité de rendre obligatoire authentification

**Comment by seblucas** [comment]
L'usage est intéressant et cela ne semble pas très à compliqué si le nom d'utilisateur est aussi l'adresse mail. Sinon c'est plus compliqué car il faut avoir une vraie gestion des utilisateurs ce qui amène de la complexité et qui ne m'interesse pas beaucoup.

Rendre obligatoire l'authentification est simple, il suffit de modifier le `.htaccess`

**Comment by hugoheitz** [comment]
merci pour le retour.
j'ai essayé et trouvé une solution plus simple : utiliser un smartphone ou tablette et un chromecast pour afficher sur la TV, cela fonctionne très bien.
en couplant cette solution avec quelques évolutions mineures sur la partie envoi d'email, cela fonctionnera très bien pour toutes les tablettes disposant d'une fonction Send to (donc les kindle), pour les autres il sera toujours possible d'envoyer l'email à une boite aux lettres et récupérer le fichier via USB ou téléchargement depuis la tablette directement.
j'ai ouvert une autre issue pour les fonctionnalités sendto.

j'ai modifié mon authentification .htaccess pour avoir authentification à l'extérieur et aucune authentification quand je suis dans le réseau wifi à domicile. Ca fonctionne bien.
J'ai effectivement utilisé l'email comme authentification mais je suis d'accord, l'objectif n'est pas de complexifier l'outil avec gestion des utilisateurs, ici la problématique est de savoir comment on peut partager une bibliothèque ou des informations concernant un livre quand il s'agit d'une bibliothèque électronique, le système de la TV marche bien, l'usage n'est pas très courant et le chromecast ne s'allume que quand la TV s'allume.

ci-dessous présentation de ce que cela donne en utilisant MyReadings, interface reposant sur COPS.
![biblio_cops_myreadings_sur_tv_1](https://cloud.githubusercontent.com/assets/972023/23554058/be47a0d4-0023-11e7-94ca-89e1c23e2ead.jpg)

**Comment by hugoheitz** [comment]
With the improvements to sendto functionalities, it will be ok.
