### ISSUE TITLE
"Recent added" turned empty

### ISSUE THREAD

**Issue by Aurigod** [seblucas/cops#325]
Suddenly the page "recent added" turned empty.
I've updated calibre library to version 2.80. Perhaps it's the reason ?
thanks for help.

**Comment by seblucas** [comment]
I updated to latest and did not have any issue, I guess you spotted the error yourself

**Comment by Aurigod** [comment]
Yes it was my SD card that was in errors I/O.Thanks.


-------- Message d'origine --------De : Sébastien Lucas <notifications@github.com> Date : 03/03/2017  11:09  (GMT+01:00) À : seblucas/cops <cops@noreply.github.com> Cc : Aurigod <jeanluc.garioud@gmail.com>, State change <state_change@noreply.github.com> Objet : Re: [seblucas/cops] "Recent added" turned empty (#325) 
I updated to latest and did not have any issue, I guess you spotted the error yourself

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/seblucas/cops","title":"seblucas/cops","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/seblucas/cops"}},"updates":{"snippets":[{"icon":"PERSON","message":"@seblucas in #325: I updated to latest and did not have any issue, I guess you spotted the error yourself"}],"action":{"name":"View Issue","url":"https://github.com/seblucas/cops/issues/325#issuecomment-283915939"}}}
