### ISSUE TITLE
Improvements to send to functionality and documentation

### ISSUE THREAD

**Issue by hugoheitz** [seblucas/cops#326]
I did configure the send to functionality.

It is easier to crawl COPS on a smartphone and send the book to your ereader...
![smartphone avec cops](https://cloud.githubusercontent.com/assets/972023/23830925/38af720e-0716-11e7-899e-fbbec8b93fca.png)

of course, you need an ereader that supports sendto function
![kindlepaperwhite](https://cloud.githubusercontent.com/assets/972023/23759644/a3e1e74e-04ed-11e7-8242-1ef1b622abf4.jpg)

or an application on your smartphone or tablet, this application could be able to open the file received by mail. (like Aldiko for example)
![aldiko-e-reader-android-2 0-2](https://cloud.githubusercontent.com/assets/972023/24704277/43236e12-1a07-11e7-963c-be48c77daad8.jpg)

In the configuration file, you can modify 
the mail from
the mail account to address the mail
it is possible to use Gmail account BUT for that you need to authorize the gmail account to allow other applications to use Gmail (configuration in Gmail account). there is no information about that, maybe it is possible to add that in the config file (as comments) and in the FAQ ?

There is no possibility to modify the mail subject
"Sent by COPS : <title of the book>"
Is it possible to add a config line to modify the mail subject (at least the beginning) and to offer the possibility to use the title chosen for the library or to be completly free ?

The choice of mail destination is offered once in the session, if you do a typo and type wrong the mail address then the choice is recorded for the session.
Is it possible to offer the possibility to change mail address while in the session ?
maybe with another mail icon button and an interrogation point ?

The format of the book which is sent is not clear because the mail button does not provide this information. 
Is it possible to create a mouse over information that tells which format of the book will be sent ?
What are the rules ?
mobi by default ? epub if it is the only format available ?

And last thing, is it possible to provide the mail button in the list of books when doing a search or in the last 50 books ?
When I did add the books in Calibre, I would like to be able to send some of the last directly in my kindle using COPS interface.
It could also be an option available in the config file.

For all this information to be used effectively, documentation in the FAQ should be useful.

Thanks for the work !

**Comment by seblucas** [comment]
First the Wiki on Github is completely open so you can enhance as much as you want. I receive notifications and only check what was done.

Then there are many questions so let's make a very long post : 

> it is possible to use Gmail account BUT for that you need to authorize the gmail account to allow other applications to use Gmail (configuration in Gmail account). there is no information about that, maybe it is possible to add that in the config file (as comments) and in the FAQ ?

I just tested the Gmail integration where I coded it but never used it, I use my own smtp server so never had the problem. I guess you can create a new Wiki item about mail configuration in COPS.

> There is no possibility to modify the mail subject
> "Sent by COPS : <title of the book>"
> Is it possible to add a config line to modify the mail subject (at least the beginning) and to offer the possibility to use the title chosen for the library or to be completly free ?

That won't be hard to do, I'll see what I can do.

> The choice of mail destination is offered once in the session, if you do a typo and type wrong the mail address then the choice is recorded for the session.
> Is it possible to offer the possibility to change mail address while in the session ?
> maybe with another mail icon button and an interrogation point ?

You can change it in the configuration page : http://cops-demo.slucas.fr/index.php?page=19

> The format of the book which is sent is not clear because the mail button does not provide this information.
> Is it possible to create a mouse over information that tells which format of the book will be sent ?
> What are the rules ?
> mobi by default ? epub if it is the only format available ?

The rules are here : 
https://github.com/seblucas/cops/blob/master/lib/Book.php#L265
from least interesting format to best interesting format (so MOBI is always prefered)

I agree a mouse over information would be good

> And last thing, is it possible to provide the mail button in the list of books when doing a search or in the last 50 books ?
> When I did add the books in Calibre, I would like to be able to send some of the last directly in my kindle using COPS interface.
> It could also be an option available in the config file.

That is harder to do and big attachments could fail for many reason which are hard to debug. I agree it could interesting but it's harder to do.

> For all this information to be used effectively, documentation in the FAQ should be useful.

You can start it in the Wiki, I'll update it if I see some errors or enhancements.

**Comment by hugoheitz** [comment]
Hi, 
Thanks for the feedback.

I started the wiki update.

About the last improvement, there is a misunderstanding, when I speak about a mail button in the list of books, it is not for all the books found, it is a mail button for each book. 
Actually I have to go in each book to be able to send it with mail button.
(whereas I can download each book directly from the list).
As seen in the screen : on each book, you can directly download but not send.
![liste_livres_cops](https://cloud.githubusercontent.com/assets/972023/23554791/caec990e-0026-11e7-86b9-36ff9601b53a.PNG)
(OK this is a wrong example because the website is not configured to provide send to functionality but I hope you'll get my point).

Thanks for the information about the mail modification, it seems basic but is very useful. I like to share my new favorite books with friends and it is a great feature to be able to change the destination mail.
What I meant with the possibility to have a different mail button is to get the possibility to get each time a dialog box that asks the destination mail. Maybe it wont be useful a lot of time so it would need to be configurable in the configuration zone of COPS to appear or disappear as wished.

I would be glad to see and test the evolutions.

Thanks again for your work.

**Comment by hugoheitz** [comment]
Thanks for the modifications. It is great.

Would it be possible to configure the demo site (http://cops-demo.slucas.fr/index.php) to have an email option configured (to let the mail icon appear) even if the mail itself does not work (to avoid issues with your provider) ?

It would help present the solution to people who have kindle but maybe did not know that it is available. 
Like me, I have my kindle for a year and a half and it is only now that I realize that the email option is more easy to use than the internet navigator on the kindle itself.

I would like to modify the existing mail icon to explain more precisely what I have in mind 
a mail icon with a star (like a favorite), it means you will send to your current kindle
a mail icon with a question mark, it means you will send to someone new and needs to know who (so a dialog box will appear)

**Comment by hugoheitz** [comment]
After a look at the icons available on glyphicons, I would propose this for the first one 
a mail icon with a star
<span class="glyphicons glyphicons-message-new"></span>

and this one for the other
a mail icon with a question mark
<span class="glyphicons glyphicons-message-plus"></span>

the question mark is this one below but there is no mail icon that sums it all...
<span class="glyphicons glyphicons-question-sign"></span>

**Comment by hugoheitz** [comment]
I just bought a new ereader (kindle) supporting the sendto functionality for a member of my family.

Using COPS on a smartphone and the sendto functionality to put books on the selected kindle ereader or app is great BUT with the current implementation, it misses something, you can't select easily where you want to send, you have to provide an email address.

So I thought "what Amazon do ?" 

In fact the answer is quite simple : Amazon provides a list of all ereader devices or apps connected to the account, this list is available on the book details page.
![amazon-liste-destination-ebook-kindle-devices-and-apps](https://cloud.githubusercontent.com/assets/972023/24098445/b67f4024-0d6a-11e7-9cb0-a457dde9ab9a.PNG)

What I would like is for COPS to provide the same functionality 
a functionality that can be modified with the config section.

First a question would be asked
Do you want to use multiple emails ? (checkbox)

If checked, it would be possible to provide as many items as wished with a name and email.
default device : John's reader / email : john.doe@kindle.com
2nd device : Bob's reader / email : bob.doe@kindle.com
3rd device ...
and so on
You can add / modify / delete an entry

mockup
![mockup amelioration sendto-with list](https://cloud.githubusercontent.com/assets/972023/24098802/a9a06bf6-0d6c-11e7-925c-592b7a3829e6.PNG)

of course, there would be a : "other destination" and that would open a dialog box to enter the email address.

It would be a huge improvement to the functionality and it would address the problems explained in #326I just bought a new ereader (kindle) supporting the sendto functionality for a member of my family.

Using COPS on a smartphone and the sendto functionality to put books on the selected kindle ereader or app is great BUT with the current implementation, it misses something, you can't select easily where you want to send, you have to provide an email address.

So I thought "what Amazon do ?" 

In fact the answer is quite simple : Amazon provides a list of all ereader devices or apps connected to the account, this list is available on the book details page.
![amazon-liste-destination-ebook-kindle-devices-and-apps](https://cloud.githubusercontent.com/assets/972023/24098445/b67f4024-0d6a-11e7-9cb0-a457dde9ab9a.PNG)

What I would like is for COPS to provide the same functionality 
a functionality that can be modified with the config section.

First a question would be asked
Do you want to use multiple emails ? (checkbox)

If checked, it would be possible to provide as many items as wished with a name and email.
default device : John's reader / email : john.doe@kindle.com
2nd device : Bob's reader / email : bob.doe@kindle.com
3rd device ...
and so on
You can add / modify / delete an entry

mockup
![mockup amelioration sendto-with list](https://cloud.githubusercontent.com/assets/972023/24098802/a9a06bf6-0d6c-11e7-925c-592b7a3829e6.PNG)

of course, there would be a : "other destination" and that would open a dialog box to enter the email address.

It would be a huge improvement to the functionality and it would address the problems explained in #326

**Comment by hugoheitz** [comment]
I've tested the cops-1-1-0 release, specifically for the mail subject configuration in the config file.
It does not work with Gmail and since I use Gmail, I was not able to validate it.

Is it possible to get the same feature for Gmail ?

**Comment by hugoheitz** [comment]
I have tested the solution with GMX and it works fine.
As I have opened other issues to identify each issue listed in this first one, I will close this issue and follow the other ones.
