### ISSUE TITLE
Email functionality config change in V1.1.0

### ISSUE THREAD

**Issue by CHBMB** [seblucas/cops#335]
So updated the docker container to install composer and found that emailing is no longer working.

`Message could not be sent.Mailer Error: Invalid address:  (punyEncode) COPS`

The contents of my config-local.php are 
```     $config['cops_mail_configuration'] = array( "smtp.host"     => "smtp.gmail.com",
       					         "smtp.username" => "email@gmail.com",
						 "smtp.password" => "password",
						 "smtp.secure"   => "ssl",
						 "address.from"  => "COPS"
```

Turns out the fix is easily discovered from the error message.  Just alter config_local.php to 

```     $config['cops_mail_configuration'] = array( "smtp.host"     => "smtp.gmail.com",
       					         "smtp.username" => "email@gmail.com",
						 "smtp.password" => "password",
						 "smtp.secure"   => "ssl",
						 "address.from"  => "COPS@ebook.com"
```

I know this is a config issue rather than a problem with COPS, but thought it might be useful for others if they ran into the same problem as me.....

**Comment by seblucas** [comment]
Thanks for the notice, I guess the upgrade PHPMailer is checking that now.

Will you take care of updating https://github.com/linuxserver/docker-cops/blob/master/root/defaults/config_local.php#L69 ?

**Comment by marioscube** [comment]
The "address.from" probably just needs to have a valid e-mail address format.

wit my e-mail app the "From" in an e-mail is $config['cops_title_default']. If that is (=) COPS the "From" is COPS :-)

**Comment by seblucas** [comment]
@marioscube 
that's the problem that exists with the default docker image.

I've seen the PR : https://github.com/linuxserver/docker-cops/pull/16

Thanks

**Comment by CHBMB** [comment]
@seblucas Yeah, I corrected it once I noticed it.   Great work on v1.1.0

@marioscube Yeah, I figured it out straight away, not so much an issue, just wanted to document it, in case others had problems. :+1:
