### ISSUE TITLE
[FEATURE REQUEST]"Read"/"Unread" button

### ISSUE THREAD

**Issue by gabriellluz** [seblucas/cops#337]
I'd like to have a button for each book so that I can mark read or not. I'd be great if that information would be stored in a custom column in the metadata.db file. I can see my custom columns on COPS but I can't actually use them like on Calibre.

**Comment by seblucas** [comment]
I'm afraid that's outside the scope of COPS (at least as I see it).

The point of COPS is to *READ* Calibre's database and never write anything to it.

So you can add your custom column in Calibre, set it in Calibre and [configure it](https://github.com/seblucas/cops/blob/master/config_default.php#L174-L210) in COPS then you can see within COPS the status of your books.
