### ISSUE TITLE
Issue after update to 1.1.0

### ISSUE THREAD

**Issue by Tos26** [seblucas/cops#338]
Hi,

I updated my COPS from version 1.0.1 to 1.1.0 and now I have only a blank page without error message.
I have PHP 5.4.45 on my server.
I saw this page on [mobileread](https://www.mobileread.com/forums/showpost.php?p=3500340&postcount=1498). Is it a symptom linked to this subject and if yes, is PHP 5.6 mini the only solution to fix this issue?

**Comment by seblucas** [comment]
Can you get PHP error log ?

**Comment by Tos26** [comment]
Hi seblucas,

Here is the php error log:

`2017/04/06 21:15:24 [error] 2004#0: *4184 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/cops/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/cops/config.php on line 9
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/cops/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/cops/config.php on line 9" while reading response header from upstr$
2017/04/06 21:15:25 [error] 2004#0: *4184 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.0.254, server: xx.xxx.xx.xxx, request: "GET /favicon.ico HTTP/1.1", upstream: "fastc$
2017/04/06 21:15:25 [error] 2004#0: *4184 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.0.254, server: xx.xxx.xx.xxx request: "GET /favicon.ico HTTP/1.1", upstream: "fastc$
20`

**Comment by seblucas** [comment]
Did you use the official package or did you update with git ?

**Comment by Tos26** [comment]
I updated from the ZIP on github.

**Comment by seblucas** [comment]
To be sure that this link : https://github.com/seblucas/cops/releases/download/1.1.0/cops-1.1.0.zip ?

That strange, I've tested with PHP 5.5 a few days ago, I have not tested it with PHP 5.4 for a long time to tell the truth. I'll create a docker environment to check when I'll get the time.

**Comment by Tos26** [comment]
Ok I'll test with this file.
Actually I got the cops-master.zip file from github.

**Comment by seblucas** [comment]
Then the error is normal (no composer dependencies), I guess cops-1.1.0.zip should work. Please close this ticket if it works as expected.

Thanks in advance.

**Comment by seblucas** [comment]
Travis says it works with PHP 5.4 : https://www.travis-ci.org/seblucas/cops/builds/219710874

So I'm confident ;)

**Comment by chadberg** [comment]
I did a git pull, and I am also getting an error about vendor/autoload.php from the config file. Looking at the repo, I do not see this file, so I guess I'm not surprised that it's throwing an error.

**Comment by Tos26** [comment]
Ok. 
I downloaded the right archive from releases folder and now it works fine.

Thank you and continue to work on this wonderful tool for our ebooks !
