### ISSUE TITLE
XSendFile Issue

### ISSUE THREAD

**Issue by anoril1979** [seblucas/cops#341]
Hello,
COPS loads and displays correctly on my Synology (DSM5) BUT I can't download any eBooks.

I have some cover displayed, but not all and none of the eBook are downloadable.

In Apache Error Log, I can read this but can't understand what it means:
```
[Sun Apr 23 15:51:18 2017] [error] [client 192.168.1.2] (20023)The given path was above the root path: xsendfile: unable to find file: /volume1/Documents/Biblioth\xc3\xa8que/Daeninckx, Didier/Le Geant Inacheve (9110)/cover.jpg, referer: http://holawan/Library/index.php?page=7&id=966
[Sun Apr 23 15:51:20 2017] [error] [client 192.168.1.2] (20023)The given path was above the root path: xsendfile: unable to find file: /volume1/Documents/Biblioth\xc3\xa8que/Daeninckx, Didier/Le Geant Inacheve (9110)/Le Geant Inacheve - Daeninckx, Didier.epub, referer: http://holawan/Library/index.php?page=7&id=966
```

I have then search the net for XSend issue of that kind and found I should modify the XSend settings int Apache conf. I found a "conf/extra/mod_xsendfile.conf-user" file and updated the "XSendFilePath" variable with "/var/services/web /volume1/Documents" then restarted Apache. With no success.

Is the problem related to accentuated files and folders? Is it a XSend setting issue or Apache issue?

Regards,

**Comment by seblucas** [comment]
It's a problem with DSM. The easiest way for you will to disable it (leaving [this line](https://github.com/seblucas/cops/blob/master/config_default.php#L73) empty).

I also guess that the accentuated does not help, I tried to avoid them at all cost (especially on embedded Linux like your NAS).

**Comment by anoril1979** [comment]
It works! great! (I feel dumb...)
