### ISSUE TITLE
COPS Basic authentication no longer works?

### ISSUE THREAD

**Issue by marioscube** [seblucas/cops#342]
Can someone confirm that COPS Basic authentication (see Wiki) no longet works with:

$config['cops_basic_authentication'] = array(); in confil_local.php
and
$config['cops_basic_authentication'] = array('username' => 'user', 'password' => 'xxxxx'); in config_local.user.php

I tried on a new install of COPS (version 1.1.0) with Debian Jessie.

**Comment by CHBMB** [comment]
Yep, I've had a report pn someone using the docker container that this no longer works.

**Comment by marioscube** [comment]
As a workaround:

Change a line in config.php from 

**require_once** dirname(__FILE__) . '/' . $user_config_file;
to
**require** dirname(__FILE__) . '/' . $user_config_file;

I do not know if this is even a "good solution to this problem", but it fixed my problem! 

All credits to **@chadberg** for finding out what went wrong in cops.

**Comment by CHBMB** [comment]
@marioscube Any reason why we shouldn't do a PR for this?

**Comment by marioscube** [comment]
No reason at all. @seblucas asked for it in #344 .

Go for it! Just credit @chadberg ;-)

**Comment by chadberg** [comment]
Glad to see it resolved. Thanks for making a pull request, I would have gotten to it this afternoon with confirmation from others, but you beat me to it! :smile_cat:

**Comment by CHBMB** [comment]
@chadberg I'm just very grateful you figured it out man!

**Comment by seblucas** [comment]
Fixed in #345
