### ISSUE TITLE
[QUESTION] - Any chance of a new 1.1.1 release?

### ISSUE THREAD

**Issue by CHBMB** [seblucas/cops#347]
Hi Seb,

After this fix #345 is there any chance you could push a  1.1.1 release so I can incorporate this fix into the docker image, rather than having to change the dockerfile temporarily to do a git clone?

That would be awesome, Thanks.

**Comment by seblucas** [comment]
I've updated the Changelog, I'll wait a day in case @horus68 has some new translation items from Transiflex and I'll make the new release

**Comment by horus68** [comment]
@seblucas done here for translations: https://github.com/seblucas/cops/pull/349

**Comment by seblucas** [comment]
Done

**Comment by CHBMB** [comment]
Thanks gents. @seblucas @horus68
