### ISSUE TITLE
Interface option to mimic a real library

### ISSUE THREAD

**Issue by hugoheitz** [seblucas/cops#351]
As explained in the wiki, it's possible to cast the interface to a big TV screen.

What I would like to get is an interface option to mimic a real library. 
To show the edges and not the covers...

Would it be possible to implement a picture in COPS ? 
There could be a way to implement the toolbar and the picture below...
![22403566-digital-library-isolated-on-a-white-background](https://cloud.githubusercontent.com/assets/972023/25741900/36559f46-318d-11e7-82f6-32d6721ee45e.jpg)

**Comment by horus68** [comment]
Prepare yourself...
![8ef4e2ed7dc3deb12ff95726dbcdbbe8](https://cloud.githubusercontent.com/assets/3055443/25743517/b8e3a92c-318c-11e7-9a23-6d928ea55a21.jpg)

Nothing against the concept implementation but i do prefer the cover browsing (and I'm a librarian).
If anything needs to evolve is to make all views like the recent
As for me I would prefer a modern interface (like the ones we can get on almost all APPS using OPDS)
![unnamed](https://cloud.githubusercontent.com/assets/3055443/25744262/c926ad12-3190-11e7-9bc8-635b362a2ad8.png)

**Comment by hugoheitz** [comment]
In order to do that, it's possible to use MyReadings
https://github.com/sbdomo/MyReadings
It's based on COPS code !
But I believe it's hard to provide this type of interface if you want it to be ereader compatible.
That's why I think about that in an option.
That would be cool if in the parameters it would possible to change the style to something like MyReadings.

**Comment by horus68** [comment]
Actually bootstrap template for Cops already can do some of my requests.

http://cops-demo.slucas.fr/index.php?page=10
![cops_bootstrap](https://cloud.githubusercontent.com/assets/3055443/25750427/9a9e4752-31a9-11e7-9a14-4305c312f26d.PNG)

**Comment by CHBMB** [comment]
MyReadings looks like a dead project to me.  No commits for nearly three years.....

**Comment by hugoheitz** [comment]
I hope the new version will contain a bootstrap template.
