### ISSUE TITLE
Edit books and add new functionality

### ISSUE THREAD

**Issue by ebartlomiej89** [seblucas/cops#352]
Do you anticipate adding a new functionality. I want to add new books via www interface and edit existing items in my library.

Thank you for informations.

Best Regards
Bartłomiej Ekiert

**Comment by horus68** [comment]
COPS is just a web interface for your Calibre library. Any edits on books title and so on needs to be done in Calibre.

**Comment by seblucas** [comment]
The question has been already asked a few time (meaning I should make it clear in the README). COPS was never meant as a plain replacement for Calibre. Calibre is a marvellous tool with a lot (A LOT) of features. I don't have the time / resources / motivation to match them.
