### ISSUE TITLE
QNAP Server Blank Page

### ISSUE THREAD

**Issue by hoffma0901** [seblucas/cops#358]
I've installed cops onto my QNAP TS-431. Webserver is enabled and the cops files are stored in /web/cops/, config_local.php is edited.
My books are stored at /share/eBooks/.
But when I try to open the COPS interface in my web browser (192.168.xxx.xx/cops) only a blank page appears.
On the other hand i tried bicbucstriim which works fine.

As mentioned in an other issue I tried to edit the rights with chmod und chown of the bookshare. No luck so far...

**Comment by marioscube** [comment]
What is the output of:

http://192.168.xxx.yyy/cops/checkconfig.php

**Comment by hoffma0901** [comment]
Blank scren as well...

**Comment by marioscube** [comment]
Try reinstalling cops from 

https://github.com/seblucas/cops/releases/download/1.1.1/cops-1.1.1.zip

The test with 

http://192.168.xxx.yyy/cops/checkconfig.php

**Comment by hoffma0901** [comment]
Sadly still the same issue. I got no ideas why it isn't working. I never used the php webserver before and did not change a thing according to the webserver...

**Comment by marioscube** [comment]
On your QNAP go to /web
Use an editor like nano or vi to make a file **info.php** with this content:

```
<?php
phpinfo();
?>
```

Then: http://192.168.xxx.yyy/info.php

Does this give any output?

**Comment by seblucas** [comment]
Also can you find the php logs ? it would help a lot.

**Comment by hoffma0901** [comment]
phpinfo gives me a long list of my php and server configuration. Anything special to look for?

@seblucas I've set `log_errors = On` in the php.ini but I can't find any logfiles related to php...

**Comment by seblucas** [comment]
Please paste the output of phpconfig on something like pastebin

I don't know how QNap handle php at all but finding the logs would be great

**Comment by hoffma0901** [comment]
Ok guys, I got the verbose error output of php working. I feel kinda dumb now. A missing `*/` at the end of a comment added by me in the `config_local.php` was the problem.

**Comment by seblucas** [comment]
nothing dumb about .... that's why log are so important
