### ISSUE TITLE
Missing installation instructions for systems with PHP7

### ISSUE THREAD

**Issue by nolaviz** [seblucas/cops#359]
The install instructions currently only refer to PHP5, which isn't available anymore in several distributions (Ubuntu starting with 16.04, Debian Stretch, etc.).

**Comment by seblucas** [comment]
I can confirm the COPS works perfectly fine with PHP7 or PHP7.1 (the unit test are tested by travis : https://travis-ci.org/seblucas/cops).

Can you specify which install instruction are wrong ?

**Comment by nolaviz** [comment]
On the main page, the prerequisites section says

> On any Debian based Linux you can use : aptitude install php5-gd php5-sqlite php5-json php5-intl

This won't work when the distro only has php7.
(The differences aren't significant, I agree)
