### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by marioscube** [seblucas/cops#361]
To prepare for the upcoming launch of Debian Stretch and to see if COPS still works with the new Debian version I decided to try to install COPS from the github source (git clone) on a fresh install of stretch. 

Doing this I ran into the following problem:
when:  php composer.phar install --no-dev --optimize-autoloader 
I got the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-xml * is missing from your system. Install or enable PHP's xml extension.
  Problem 2
    - The requested PHP extension ext-mbstring * is missing from your system. Install or enable PHP's mbstring extension.
  Problem 3
    - Installation request for seblucas/php-epub-meta 1.0.0 -> satisfiable by seblucas/php-epub-meta[1.0.0].
    - seblucas/php-epub-meta 1.0.0 requires ext-xml * -> the requested PHP extension xml is missing from your system.
```
This was easily resolved by:
apt-get install php7.0-xml php7.0-mbstring php7.0-zip

As far as I can remember this was not needed on Debian Jessie. (Jessie does not know/need these packages for php5.)

Maybe something for the readme?

**Comment by seblucas** [comment]
Thanks a lot for the test
