### ISSUE TITLE
File /volume1/calibre/metadata.db not found, 

### ISSUE THREAD

**Issue by ric80231** [seblucas/cops#362]
Hi,
I have been trying to install COPS on my Synology DS716+, running DSM 6.1.2-15132 Update 1. To date with no success. The Configuration check fails and cites the above reason. I have checked:

     - Value ofopen_basedir in your php.ini
     - The access rights of the Calibre Database
and followed the instructions in https://github.com/seblucas/cops/wiki/Howto---Synology.

With the exception of one item, that is 'Value of $config['calibre_directory'] in config_local.php'. 

As I am a novice at this sort of thing, I do not have all the knowledge I need, for instance,  where is the config_local.php file. You do not mention that detail. I have searched for it and am unable to find it.

Sincerely R A Evans

**Comment by seblucas** [comment]
Hi,

Sorry for the delay, I don't have any recent Synology Nas (mine is blocked with 5.2) to test on so I recommend you to read #332 or #277 

I won't be able to help you here.
