### ISSUE TITLE
Books not downloading - Kobo Aura One

### ISSUE THREAD

**Issue by Stanzer** [seblucas/cops#364]
Hi,

since the update of Kobo's firmware (4.4.9349), I cannot download anybook from my Cops Installation. The downloading screen very briefly shows then disappears. And the book, of course does not appear in books list, in the directory ( in Nautilus when connected to PC) or Calibre. It seems the download just fails to start.

Any hint on how to correct this behavior would be welcome. Please feel free to ask any more details you might need.

Thanks

**Comment by seblucas** [comment]
Hi,

Unfortunately it is one bug in the latest firmware from Kobo, the beta group (me included) notified of the regression but it was not fixed before the public release of latest firmware. I hope that it will be fixed soon but I can't do anything about it :( 

There is no workaround possible as the browser can't download any files.

**Comment by Stanzer** [comment]
Aw ! :-(
Thanks for your swift answer, anyway :)

**Comment by loscar72** [comment]
Hello,
I've found a thread of discussion around this problem, and it's seems that a workaround might exists... 
(Content-Disposition header with the file name and not in the URL - see below).
Any idea if it can be done in COPS ? I'm volunteer to be a beta tester !
Thanks

[https://www.mobileread.com/forums/showthread.php?s=8ba1fa63bec3f63632a54befb3319711&t=288740&page=16](url)
