### ISSUE TITLE
OPDS

### ISSUE THREAD

**Issue by DamienLGD** [seblucas/cops#371]
Hi, i uninstall my .spk on Synology and download the lastest release (1.1.1) 
So it works well with a browser or Aldiko, but i have an error on Moon reader (i need Moon reader for .cbr/.cbz)
The error is this :

"Invalidated OPDS content, please contact owner of this OPDS site to verify velow error:
At line 1, column 0: syntax error
----------------------------------------------------------------------------------------------
File not found.

With the .spk it worked well on moon reader, i don't know what is the problem..

Any idea?

Thanks

**Comment by DamienLGD** [comment]
Ok i find a way to get it work.
It works if i use http://server_ip/cops/feed.php
But it doesn't work with http://server_ip/cops (on Moon Reader)

**Comment by horus68** [comment]
- Your Moon reader is updated to latest version?
- Verify your setting on Cops (detect an OPDS reader)
https://github.com/seblucas/cops/blob/bb97fd591a2faf2bccd9c9d5b0f18ebf9297fcb6/index.php#L14

**Comment by seblucas** [comment]
I think that there is no default page for `http://server_ip/cops` : please try it on a real browser.

otherwise as shown by @horus68 , If you try to access the index.php with a known OPDS reader, COPS automatically redirect to feed.php

**Comment by DamienLGD** [comment]
Ok if i use http://server_ip/cops/index.php or http://server_ip/cops/feed.php in moon reader, it works.
But http://server_ip/cops not (i can't access to Authors/Series/Publishers/Tags/Languages/All books & Recent additions)

So it is the fault of Moon Reader which doesn't access to index.php by default? 

Without writing index.php à the end of the url, it works with Aldiko or a browser (if Aldiko i am redirect to feed.php, if Firefox to index.php)

@horus68 I didn't modify the index.php and yes it is the latest release of Moon reader.
@seblucas Congratulations for your excellent app

**Comment by seblucas** [comment]
> Without writing index.php à the end of the url, it works with Aldiko or a browser (if Aldiko i am redirect to feed.php, if Firefox to index.php)

It's strange then. I never use Moon Reader but I'm so used to write the full URL (with feed.php) that I never had the problem before with any OPDS reader.

**Comment by horus68** [comment]
MoonReader works fine for me.
Can you test using the demo library http://cops-demo.slucas.fr/

**Comment by DamienLGD** [comment]
@horus68 I tried with the demo before create this issue, but yes it works.
In fine it is not a big issue because full path of the url works, but i didn't know why it worked with the Synology package (1.0 RC2), and now with the last release i have to write feed.php (and only on Moon Reader, it still works on Aldiko)

I look the code, and it is the same thing... strange.
