### ISSUE TITLE
Possible to use on OpenWRT / LEDE?

### ISSUE THREAD

**Issue by alazyworkaholic** [seblucas/cops#373]
I think there's a lot of demand for a calibre ebook server that could run on open source router firmware (OpenWRT, LEDE, Tomato, etc.). Despite the constrained system, it's common to mount a larger filesystem on external media. A package compatible with opkg would be fantastic, and a OpenWRT howto alongside the Synology HowTo would help tremendously.

Thanks / Merci!

**Comment by seblucas** [comment]
This shouldn't be that hard, COPS only need php and a web server. But that's not something I can make myself (I know nothing about OpenWRT / LEDE except the names).
