### ISSUE TITLE
Running COPS 1.0.1-5 on Synology with DSM 6.1.3.-15152 Update 8 results in error page

### ISSUE THREAD

**Issue by fmefme** [seblucas/cops#375]
I get this error

COPS CONFIGURATION CHECK
You've been redirected because COPS is not configured properly
Database error
Check if PHP version is correct - OK (5.6.31)
Check if GD is properly installed and loaded
Please install the php5-gd extension and make sure it's enabled
Check if Sqlite is properly installed and loaded
Please install the php5-sqlite extension and make sure it's enabled
Check if libxml is properly installed and loaded - OK
Check if Json is properly installed and loaded - OK
Check if mbstring is properly installed and loaded - OK
Check if intl is properly installed and loaded - OK
Check if Normalizer class is properly installed and loaded - OK
Check if the rendering will be done on client side or server side
Client side rendering 
Check if Calibre database path is not an URL - OK
Check if Calibre database file exists and is readable - OK
Check if Calibre database file can be opened with PHP
If the file is readable, check your php configuration. Exception detail : exception 'PDOException' with message 'could not find driver' in /volume1/web/cops/checkconfig.php:203 Stack trace: #0 /volume1/web/cops/checkconfig.php(203): PDO->__construct('sqlite:/volume1...') #1 {main}
Check if Calibre database file contains at least some of the needed tables
If the file is readable, check your php configuration. Exception detail : exception 'PDOException' with message 'could not find driver' in /volume1/web/cops/checkconfig.php:216 Stack trace: #0 /volume1/web/cops/checkconfig.php(216): PDO->__construct('sqlite:/volume1...') #1 {main}

The PHP 5.6 package 5.6.31-0053 is installed.

Any ideas?

Thnx

**Comment by seblucas** [comment]
My NAS died a few month ago and I dodn't replace it (I now trust in the cloud or I'm forced to).

Did you read the closed issue about DSM ?

**Comment by HomeLH** [comment]
I also met this problem. I wonder "Please install the php5-sqlite extension and make sure it's enabled". But I have installed sqlite3, it can not work.

**Comment by biaji** [comment]
@HomeLH Just check pdo_sqlite and there you go
