### ISSUE TITLE
404 Error in Fetch.php and download

### ISSUE THREAD

**Issue by yabdali** [seblucas/cops#376]
I installed Cops manually, set the php settings including the base directly to point to my library which is under/volume1/mycloud/books/ and have http group permissions w/r set for both the cops folder and the library. No errors when I run the config check.
My problem is when I click on any book either pdf or epub I get page can't be found 404. I tried to change the ur rewriting to 1 and I get redirect to the download page with the same error.
I have added the path of the directory in config_local.php (calibre_directory) to point to /volume1/mycloud/books/ and cops_x_accel_redirect to X-Sendfile. I didn't change calibre_internal_directory value though.
Can you please help?
DSM 6.1.4
Apache 2.2
Php 7.0
Cops 1.1.1

**Comment by marioscube** [comment]
Did you also change the value of PHP open_basedir in your Synology settings (control panel / web services) with /volume1/mycloud/books added to the list?

**Comment by seblucas** [comment]
Enabling cops_x_accel_redirect should only be done once everything is working fine, same for url rewriting

I'll close this, feel free to reopen if needed
