### ISSUE TITLE
picture how to in one windows

### ISSUE THREAD

**Issue by ybbluesky** [seblucas/cops#378]
when i user cops on pc,the big picture can not in one windows,how to let pic in one windows?

**Comment by marioscube** [comment]
@ybbluesky

What "big picture"?

Can you give an example?

**Comment by ybbluesky** [comment]
the big pic i talk is when i user cops on pc,the cover splite two or three ,pic is 
![1](https://user-images.githubusercontent.com/34271895/33747958-d3640714-dc00-11e7-9a82-c51e0785b745.png)
![2](https://user-images.githubusercontent.com/34271895/33747959-d3a45c88-dc00-11e7-99d5-45fc77b2291e.png)

but on phon ,pic is 
![3](https://user-images.githubusercontent.com/34271895/33747986-009c293c-dc01-11e7-92b0-b69e4fba9b1a.jpg)

thanks

**Comment by marioscube** [comment]
The picture cannot be scaled down (in cops).
Your PC screen has a fixed number of lines (resolution) that is smaller than the number of lines/pixels in the cover-picture (example: screen = 1024 x 768 pixels = an older small screen or 1920 x 1080 pixels = new HD screen;
cover =  1000 x 1500 pixels -> 1500 > 768 or 1080 > does not fit vertically)

On your Phone the vertical resolution is probably higher than on your PC screen. and then it works!

_NB: the epub reader in cops is not very good.
You should find another epub-reader for reading epubs on your PC and/or Phone.
For PC find an add-on to Firefox or Chrome.
For Phone there are pretty good (and inexpensive) epub readers for Android and iOS the stores._

**Comment by seblucas** [comment]
I agree with @marioscube , the epub reader was fun to code but having a full featured epub reader in COPS will be too hard to code and maintain.

I won't fix anything related to the embedded epub reader, sorry :(.

**Comment by ybbluesky** [comment]
thanks all
