### ISSUE TITLE
how th show library name in index.php

### ISSUE THREAD

**Issue by ybbluesky** [seblucas/cops#379]
when i user cops,the library name is 0,1,2,3-----,i want change 0,1,2 to the library name,what to do?
![4](https://user-images.githubusercontent.com/34271895/33748115-ba464322-dc01-11e7-9d31-15c37f80cbdc.png)

my english is  very poor ,thanks

**Comment by ybbluesky** [comment]
![5](https://user-images.githubusercontent.com/34271895/33748144-d4e83a32-dc01-11e7-8d04-ab5bb3f4c18a.png)

**Comment by marioscube** [comment]
In config_local.php add the library name(s) like this:

$config['calibre_directory'] = array ("Library name" => "/home/directory/calibre1/",
                                                       "Other library name" => "/home/directory/calibre2/",
                                                       "And another library name" => "/home/directory/calibre3/");
 
You forgot to add 

"library name" => 

to the lines(?)

**Comment by seblucas** [comment]
Exactly.

thanks @marioscube  for answering.

**Comment by marioscube** [comment]
Isn't this topic closed a bit too soon?

The topicstarter probably hasn't read it yet and given his english can he find it now?

@seblucas Good to see you are still interested in cops ;-)

**Comment by seblucas** [comment]
I am still interested in COPS, real life is a .... so I have not any time left. I'll do a Xmas release though.

The topic started should have a notification (either by mail or within Github) ....

**Comment by marioscube** [comment]
Yeah real life never leaves enough hours in a day to have fun ;-)

Still thank you for cops though. 

I wish you a Joyeux Noël and a good start in the new Year altough is't only the early days of december (but I might forget....)

**Comment by ybbluesky** [comment]
thanks all
