### ISSUE TITLE
kepub convertion for Kobo H2O edition 2 not working

### ISSUE THREAD

**Issue by ospring** [seblucas/cops#380]
Using kobo h2o edition 2 firmware 4.7 with stock experimental browser
using cops v1.1.1
with in config
  $config['cops_provide_kepub'] = '1';
  $config['cops_use_url_rewriting'] = "1";

When I try to donwload an epub, the url is rewrited to toto.kepub.epub BUT the file is downloaded to toto.epub
in http header there is : 
Content-Disposition: attachment; filename="toto.epub" 
and in the kobo filesystem you can find toto.epub file
and the kobo browser is asking in a dialog box if I want to download "toto.epub"
maybe the kobo browser is now trusting Content-Disposition.....

**Comment by seblucas** [comment]
I know Kobo has been changing a lot in the embedded browser, I'll test that.

**Comment by seblucas** [comment]
Did you enable cops_update_epub-metadata in your config_local ?

**Comment by ospring** [comment]
yes :
 
    $config['calibre_directory'] = 'D:/Goodies/Livres/';
    $config['cops_title_default'] = "test";
    $config['cops_use_url_rewriting'] = "1";
    $config['cops_update_epub-metadata'] = '1';
    $config['cops_provide_kepub'] = '1';
    $config['cops_template'] = 'default';
    $config['cops_style'] = 'eink';

**Comment by seblucas** [comment]
OK I think I reproduced it, I'll commit a partial fix in a few minutes and a full fix later this week.

**Comment by seblucas** [comment]
Partial fix in https://github.com/seblucas/cops/commit/3db12dfbed950712c17773fd45b8ef5357f87049

**Comment by ospring** [comment]
Thanks ! Will test that ASAP !

**Comment by seblucas** [comment]
I'm preparing a release can you confirm that my commit fixed your problem ?

**Comment by ospring** [comment]
Hi,

Sorry for the delay. I have applied the patch and I managed to download an epub as kepub on my kobo. So it seems to work !
Thanks !

Olivier
