### ISSUE TITLE
Synology: COPS stopped working with multiple databases

### ISSUE THREAD

**Issue by drew-kun** [seblucas/cops#387]
I have two separate calibre libraries in subfolders: `/volume1/books/library/calibre/metadata.db` and `/volume1/books/library/textbooks/metadata.db`

Previously there was a functionality for choosing library in COPS web interface...
I just had to set the path to calibre libraries as `/volume1/books/library/` and then in web interface there was a dropdown menu for choosing the calibre library.

Seems like previously COPS **recursively** detected all the `.db` files in the `/library/` path
But now seems like the path must contain `metadata.db` file otherwise it returns the following error:

![untitled](https://user-images.githubusercontent.com/10493450/37247361-76f173d4-246e-11e8-80f5-fba14e0690ac.png)

How can I get back that ability to choose between multiple calibre libraries in web interface?

**Comment by horus68** [comment]
Double check your settings for multiple database in config_default.php
https://github.com/seblucas/cops/blob/master/config_default.php#L17-L18

**Comment by drew-kun** [comment]
Thank you, that works.. but shouldn't it work the way I described above?

**Comment by seblucas** [comment]
As far as I remember, there never was a way to specify a single parent path and that COPS detect the libraries inside that directory. 

If that worked before that was certainly a bug.

I'll close this as @horus68 provided a solution.
