### ISSUE TITLE
COPS (Calibre OPDS PHP Server) HTML main script opens rather than COPS web GUI.

### ISSUE THREAD

**Issue by echofire26** [seblucas/cops#388]
Apologies as I'm fairly new to a lot of this.  I followed instructions for setting up COPS per https://pimylifeup.com/raspberry-pi-ebook-server/.  I followed all instruction and even resolved a problem I had on a previous install by resetting the Apache2 port.  However, after getting everything installed to the best of my knowledge, every time I try and access x.x.x.x/ebooks it instead downloads or opens a copy of COPS (Calibre OPDS PHP Server) HTML main script rather than the web GUI.  Any suggestions or idea would be greatly appreciated - apologies if was the wrong venu for this but I can't seem to find anything on this anywhere else.

**Comment by seblucas** [comment]
That usually mean that apache does not know how to handle PHP script. It's been a while since I used Apache, maybe check mod_php ?

**Comment by echofire26** [comment]
Thanks - not sure what I screwed up still - but I rebuilt it from scratch again and this time it's working with nginx....now I just have to figure out why I'm getting a 404 error when I try and download something.

**Comment by seblucas** [comment]
Great I'll close this one please create a new issue if needed
