### ISSUE TITLE
Update strings from Transifex

### ISSUE THREAD

**Issue by otapi** [seblucas/cops#391]
Hi, is there an admin here anymore? I fixed/edited some Hungarian strings on Transifex 1-2 weeks ago and I don't see any updates happening on the gitHub files. Can you pls commit the translation updates?

**Comment by seblucas** [comment]
Hi, I'll do that soon.

The problem with Transifex is that its notification system is (or was) quite bad so I disabled everything to avoid getting too much mail. So creating an issue is a good idea ;)

**Comment by otapi** [comment]
Great, thank you! I just localized rest of untranslated strings of HU and reviewed all of them - it's ready to PR.

**Comment by seblucas** [comment]
@horus68 thanks a lot ;)

**Comment by horus68** [comment]
PR created here: https://github.com/seblucas/cops/pull/394

**Comment by seblucas** [comment]
Merged #394 , thanks
