### ISSUE TITLE
Php7-mod-intl require icu

### ISSUE THREAD

**Issue by liladude** [seblucas/cops#395]
Hi, thank you for your hard work. Not really an issue on the system, but a problem with most small devices. I am trying to install COPS on a small LEDE device. The main problem is that php7-mod-intl needs icu which is 12 MB. Most devices are less than 8 MB in flash memory. Is there any way around?

**Comment by seblucas** [comment]
Last time I checked it wasn't mandatory 'but that was a long time ago), did you try without ? Can you share the error if you catch one ?

Thanks in advance

**Comment by seblucas** [comment]
I checked the code and I think `intl` is not needed (but I did not made an extensive test but the unit tests worked), can you try without this extension ?
