### ISSUE TITLE
DietPi

### ISSUE THREAD

**Issue by Thomas-O** [seblucas/cops#398]
Please consider helping [DietPi](https://github.com/Fourdee/DietPi) to add COPS to their catalogue.

**Comment by seblucas** [comment]
That should be hard to do at all (I don't if my help is needed). I'm personnaly using [Armbian](https://www.armbian.com/) and use the docker image.

**Comment by Thomas-O** [comment]
Sinon, qu'en est-il d'une application COPS pour NextCloud? Synchronisation multi-plateformes et service tout-en-un.

[Blacs30](https://github.com/blacs30/calibre_opds) a utilise votre travail pour creer une application serveur de calibre (sans HTML) pour nextcloud, mais il n'a pas le temps de gerer l'application.

J'espere que mon français est correct.

Thomas

**Comment by seblucas** [comment]
I have neither the knowledge of Nextcloud / Owncloud nor the interest to develop a Nextcloud plugin. Sorry :(
