### ISSUE TITLE
Two Librarys-possible one to secure with Password?

### ISSUE THREAD

**Issue by gismo2006** [seblucas/cops#400]
Hi, 

I use the last cops version with htpassword file on my NAS. Everything works fine.
Till now, i use one Library. But now i like to use a second library. Is it possible to secure only the second one whit a user/pass?
Because in my first library are books for my children, too and in the second one will be the "horror" books then.    

Thank you for this great  product. 
Sven

**Comment by marioscube** [comment]
Use "Users"

[https://github.com/seblucas/cops/wiki/User-based-config](url)

**Comment by seblucas** [comment]
@gismo2006 
Mario's answer should work fine.

another alternative is to install COPS two times (in two directories or  with two sub domains).
