### ISSUE TITLE
Which tool to add books?

### ISSUE THREAD

**Issue by OhSoGood** [seblucas/cops#403]
Hi,

Thanks a lot for this excellent project.
What tool do you use to add new ebooks (insert into database + copy files + grap metadata)? I know i could reinstall the whole calibre 'suite' for this, but I find it a little heavy. Is there any third party tool for this? Do you install calibre and then keep only calibredb (and its dependencies)?

Ideally, I would add a shared folder on my NAS (linux-based), and as soon as a ebook is dropped them, a cron or equivalent would run to add the new ebook.

Thanks in advance for your ideas!

**Comment by horus68** [comment]
COPS is "just" a frontend to the Calibre DB.
Calibre is to add and edit metadata (it also auto arrange and rename files into folders from the ebooks metadata). You will love it!
COPS will then display in browser the Calibre DB and the Ebooks Library folder
No cron job can help you as an ebook needs to have metadata and you can't guarantee its already there (unless you add it to a manager as Calibre).

**Comment by OhSoGood** [comment]
Well, i was actually looking for a tool which would just grab metadata, copy/move the epub file to the right location and add the book to the DB. But all this in command line (automation...) and in a lighter way than Calibre itself. 


I've began to try to install only the necessary Calibre packages (python ones and non-python ones) on Linux but it seems very quickly dependencies to big libs arise (Qt...). 


Any other clue? 

----- Mail original -----

De: "Horus68" <notifications@github.com> 
À: "seblucas/cops" <cops@noreply.github.com> 
Cc: "OhSoGood" <kriss.free@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 19 Juillet 2018 14:55:03 
Objet: Re: [seblucas/cops] Which tool to add books? (#403) 


COPS is "just" a frontend to the Calibre DB. 
Calibre is to add and edit metadata (it also auto arrange and rename files into folders from the ebooks metadata). You will love it! 
COPS will then display in browser the Calibre DB and the Ebooks Library folder 
No cron job can help you as an ebook needs to have metadata and you can't guarantee its already there (unless you add it to a manager as Calibre).

**Comment by XtracT** [comment]
@OhSoGood I use calibre-web as a frontend for my library in devices with proper web-browsers, it allows upload / metadata grabbing + other goodies. On the ereader side COPS is just much better due to its simplicity.

**Comment by seblucas** [comment]
I also use Calibre / Calibre-web. I think that the only tool available.
