### ISSUE TITLE
Show more columns in book details

### ISSUE THREAD

**Issue by isra00** [seblucas/cops#410]
Currently, only Authors, Publisher, Publication Year, Tags, Languages and Summary are being shown in the book details. It would be useful to have the other default columns (Identifiers, Date, Size) plus the custom ones.

Custom columns can be shown in the home page through the `cops_calibre_custom_column` config. It would be nice to have either the same config or a new one to control which custom columns are shown in the book details page.

**Comment by horus68** [comment]
Edit your config_local.php file:

```
    /** Custom columns - value names from Calibre - Visible in entry page */
    $config['cops_calibre_custom_column'] = array ("xxx1", "xxx2");

    /** Custom columns - value names from Calibre - Visible in listing pages */
    $config['cops_calibre_custom_column_list'] = array ("xxx1", "xxx2");

    /** Custom columns - value names from Calibre - Visible in Book details page */
    $config['cops_calibre_custom_column_preview'] = array ("xxx1", "xxx2");
```

xx1 and xx2 are to be changed for your calibre custom column... and you can have more values and different order by page type):

**Comment by isra00** [comment]
Thank you! I works like a charm
