### ISSUE TITLE
Translations - Language names updates

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#413]
This is a call to action for translators.
There are 9 new strings to translate (they are just language names). You can also translate any old strings and proofread the translation just using your computer/mobile internet browser, no software to install.

Please enter Cops Transifex Project at
https://www.transifex.com/rberec/cops/

**Its so easy!**
![cops_transifex_strings](https://user-images.githubusercontent.com/3055443/46458649-6656c680-c7ae-11e8-8157-ae495b1ac4e9.png)

In a week from today I will send all the work done to Cops github as a PR to be merged with the current Cops version.
Note: if you are not yet a translator please use Transifex page to send a request to become one.
Translations will be updated regularly, so you can keep on translating. 
Did I mention that it's FREE?!

**Translation stats:**
![cops_transifex_geral](https://user-images.githubusercontent.com/3055443/46458655-6c4ca780-c7ae-11e8-8129-a7037a9fb464.png)

**Comment by seblucas** [comment]
Thanks @horus68 for doing this.

I've done my part with French and my wife will update Italian soon (if nobody is faster than her).
