### ISSUE TITLE
COPS Blank Page

### ISSUE THREAD

**Issue by itchygrub** [seblucas/cops#427]
Synology DS218play 
Apache 2.4
Php 7.2
Configured as per instruction
Blank page
Run check shows blank page

**Comment by marioscube** [comment]
Did you download and install cops 1.1.2 (release) or did you install the latest code with git or zip file?

Did you test your php install?

**Comment by itchygrub** [comment]
Download from bit.
No what script for install

**Comment by marioscube** [comment]
Install cops version 1.1.2 with this link:

[](https://github.com/seblucas/cops/releases/tag/1.1.2)
then try again.

**Comment by itchygrub** [comment]
The checkconfig works.
Using Marian
7.2.13
Correct path for calibre db
Says missing 
Jason
mbstring
Normalized
Into
libxml
GD

**Comment by marioscube** [comment]
PHP 7.2 should be supported in cops.

Can you check if the missing php modules are installed.

**Comment by itchygrub** [comment]
File ./volume1/calibremetadata.db not found
 ( /volume1/calibre/) in open_basedir [lost all other settings] though
All modules loaded

**Comment by marioscube** [comment]
Use absolute path in config_local.php. 

Do not use ./vol.... unless the calibre database is “inside” the cops directory.

**Comment by itchygrub** [comment]
Cops is in webroot

**Comment by itchygrub** [comment]
Does that mean /calibre

**Comment by itchygrub** [comment]
Is this installed as a package or is install in the web directory.
The metadata file is in calibre directory.
Was created in Windows version of calibre.
Directory was deleted recreated.
Apache / php7  uninstalled installed 
Instqlled into web/cops112
openbase_dir and .ini  file read
./calibre/
Modules loaded ok
Missing database file

**Comment by marioscube** [comment]
You are almost successful.

Read the part on open_basedir in https://github.com/seblucas/cops/wiki/Howto---Synology

Add to setings open_basedir  /volume1/web/cops212/calibre

**Comment by itchygrub** [comment]
do i move my calibre directory under the cops directory as it is in the root of volume1

**Comment by marioscube** [comment]
For testing:
- move /volume1/calibre to /volume1/cops112/calibre
- config_local.php = $config['calibre_directory'] = './calibre/';

**Comment by itchygrub** [comment]
It seems to work.

**Comment by marioscube** [comment]
Point network share in Synology settings to 
/volume1/web/cops112/calibre

**Comment by seblucas** [comment]
@itchygrub 
Do you still have a problem with COPS / network share ?
