### ISSUE TITLE
Own-/Nextcloud installation

### ISSUE THREAD

**Issue by frschnet** [seblucas/cops#431]
How can i install cops in Own-/Nextcloud as announced?
thanks in advance!

**Comment by seblucas** [comment]
You can't directly .... You can use owncloud / nextcloud to sync your calibre directory and next install COPS and make it use your owncloud directory (while fixing some access rights IIRC).

Can you tell where it's announced because I can't remember writing something like this

**Comment by horus68** [comment]
> Can you tell where it's announced because I can't remember writing something like this

Maybe this page should be more clear https://hub.docker.com/r/lsioarmhf/cops/

**Comment by frschnet** [comment]
Sorry, I did understand this to be a "Nextcloud Installation":
https://blog.slucas.fr/projects/calibre-opds-php-server/
...With Dropbox / Owncloud it’s very easy to have an up to date OPDS content server....
same text like under ..hub.docker...
Thank You, will tryout.

**Comment by seblucas** [comment]
I've commited a clarification in the README it shoud propagated to Docker fairly quickly. I'll push it later tonight.
