### ISSUE TITLE
Translation updates for v1.1.3 - Join to translate online

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#433]
I'm planning a translation refresh and creating a new PR that will include all languages in the next day or two.

If you want to collaborate please take a look into Transifex project and translate/revise your language. 
It will take minutes (almost 100 lines to translate, not considering the language names!).
Many are 100% done!

https://www.transifex.com/rberec/cops

![Transifex](https://user-images.githubusercontent.com/3055443/58277642-14d96700-7d92-11e9-87bb-c8aaad5b1064.png)

**Comment by marioscube** [comment]
Updated "Dutch" to 100%.
(Only language names.)

**Comment by Dracxabi** [comment]
Updated "Spanish" to 100% and I'm viewing my other language Basque.

**Comment by seblucas** [comment]
Thanks a lot, I'll merge it quickly when @horus68 makes the PR. I'll release a new version at the end of the month

**Comment by horus68** [comment]
@seblucas done here: https://github.com/seblucas/cops/pull/438

**Comment by seblucas** [comment]
done thanks ;)
