### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by mikrofree** [seblucas/cops#436]
Bonjour,

return @create_function ('$it', $func);

Sous php 7.3, il faut ajouter @ dans vendor\seblucas\dot-php\doT.php, sinon gros bug au lancement de l'application.

Tester sur  O2Switch, php7.3 (avec php7.2, le problème d'affichage n'existait pas).
J'ai également corrigé dans le fichier index.php le "deprecated" comme préconisé par seblucas
Cordialement
Pascal

Hello,

return @create_function ('$it', $func);

Indeed, under php 7.3, you have to add @ in vendor\seblucas\dot-php\doT.php, otherwise big bug when launching the application.

Test on O2Switch, php7.3 (with php7.2, the display problem did not exist).
I also corrected in the index.php file the "deprecated" as recommended by seblucas
Sincerely
Pascal

**Comment by horus68** [comment]
Confirmed: COPS working fine with PHP 7.3.6 (and PHP 5.5.12) after changing
vendor\seblucas\dot-php\doT.php, line 94
from
`        return create_function ('$it', $func);`
to
`        return @create_function ('$it', $func);`

I'm using the files from actual GIT master branch. I will create a PR to make this possible to include as a FIX

**Comment by seblucas** [comment]
Again sorry for the delay.
I'll take care of that tomorrow evening.
