### ISSUE TITLE
Small Issue "-CLEAR" Labels

### ISSUE THREAD

**Issue by Dracxabi** [seblucas/cops#439]
Hi all, 

A small issue with labels, I active the option "Active filter by label" and I select for example label "Sci-Fi" and I see the labels of all books, but appared a label "-CLEAR". This Label are inactive unlike the others.  

I think a small issue,  I test with other themes, diferents labels ... I attach a screenshot if you need more information ask me. 

Thanks you. 
![-Clear Label issue COPS](https://user-images.githubusercontent.com/11947547/59636226-4b1cc300-9153-11e9-9e9f-e1feda3f63c6.JPG)

**Comment by horus68** [comment]
Same report here
https://github.com/seblucas/cops/issues/304

**Comment by seblucas** [comment]
@Dracxabi  This label allow to remove all other filters

@horus68 I know this string is not translated. The problem is that's not that easy. I'll spend 1/2 hour on this and see what I can do

**Comment by seblucas** [comment]
Fix in #304
