### ISSUE TITLE
Favicon transparency error

### ISSUE THREAD

**Issue by horus68** [seblucas/cops#440]
Actual favicon used by cops has an error with transparency, rendering as black space
Most probably it was caused by a resizing (when creating Favicon the original source must be square)
See:
![demo_error](https://user-images.githubusercontent.com/3055443/59680545-7b9f4400-91c9-11e9-9e78-77c7e64ef07e.png)

I found the image autor is tonev - https://www.deviantart.com/tonev
Files: https://www.deviantart.com/tonev/art/Vista-book-icons-127309273

Doing a revised version from the Tonev's shared PNG file (removing also some shades), the error is gone but the image doesn't stand out too. :(

See my example:
![fixed](https://user-images.githubusercontent.com/3055443/59680655-c91bb100-91c9-11e9-8329-e4b121843eb8.png)

Note: I used https://realfavicongenerator.net/ to create the favicon file
Now making a PR with the file. Use it if you need a quick fix!

**Maybe choosing a new icon?**
A cleaner and simple file would be better. 
For ready ones, get some ideas here: https://ya-webdesign.com/explore/books-emoji-png
But a file created from a vector source would be better!
https://www.flaticon.com/free-icons/book
http://www.iconarchive.com/search?q=book
https://iconmonstr.com/?s=book
https://thenounproject.com/search/?q=book

**Comment by seblucas** [comment]
Thanks for the links : I like this one : https://commons.wikimedia.org/wiki/Category:Book_icons#/media/File:Book_(5848)_-_The_Noun_Project.svg

What do you think ?

I also replacing all the icons will be good

**Comment by horus68** [comment]
Perfect image. Its also possible to include the name (COPS) on the left and make it square.
Do you want me to create the images?

Color preferences and including COPS word?
Color Hex 607b8b Light Sky Blue 4 - https://www.color-hex.com/color/607b8b
See https://github.com/seblucas/cops/issues/246#issuecomment-171976657

**Comment by horus68** [comment]
I'm not a designer but... here we go!


### v1
![v1](https://user-images.githubusercontent.com/3055443/59756661-1bb8a400-9282-11e9-889f-d223264c02fb.png)



### v2
![v2](https://user-images.githubusercontent.com/3055443/59756662-1c513a80-9282-11e9-8150-162a8d52ad03.png)



### v3
![v3](https://user-images.githubusercontent.com/3055443/59756663-1c513a80-9282-11e9-95f0-843381279930.png)




### v4
![v4](https://user-images.githubusercontent.com/3055443/59756664-1c513a80-9282-11e9-9598-4ce305330e7b.png)

**Comment by seblucas** [comment]
I like v5 
What do you think ?

**Comment by horus68** [comment]
ok from me
Will create a PR for this tomorrow
