### ISSUE TITLE
Clean installation fails

### ISSUE THREAD

**Issue by BorisAnthony** [seblucas/cops#447]
Bonjour!

I followed the installation instructions—both variations—which are simple enough, but both produce this error:
`Fatal error: Cannot declare class ComposerAutoloaderInitc9425bf936bb49b322e72c9b2a811540, because the name is already in use`

Download, edit config, point browser at it: error.
Composer, edit config, point browser at it: error.

PHP 7.3.6, locally on Mac

How to proceed?

**Comment by seblucas** [comment]
Will try it later tonight.

I have to admin I do not test enough with latest PHP version, that will be the goal of next major version of COPS : remove support for PHP 5.X and only support PHP 7.2 or later

**Comment by horus68** [comment]
I had no problem using v1.1.3 with PHP 7.3.6
System: localhost / Windows 10 / Wamp / PHP 7.3.6

Including an image with PHP settings (note: those are my defaults, do not consider as a requirement for COPS):
![cops_736-](https://user-images.githubusercontent.com/3055443/60036587-75b4d180-96a7-11e9-8f66-60952a1b578e.png)

**Comment by seblucas** [comment]
I also tested with linux / PHP 7.3.6 and everything is working fine. Closing this issue, please open another one if you can provide more information
