### ISSUE TITLE
Synology COPS Update

### ISSUE THREAD

**Issue by Salvora** [seblucas/cops#451]
I have been using synocommunity package with no problem for some time now but no update came for a long time now. Is it going to be updated?

Another thing I want to ask is, can I download latest zip package and copy/paste the contents to my COPS installation folder on the Synology so that it is updated?

**Comment by marioscube** [comment]
The Synocommunity Packages are not made by the developer of COPS.

On DSM 5 I downloaded and unzipped the "release" package from this site, configured it (copy from your old cops install) and it worked.
Don't know about DSM 6 but try it!

**Comment by seblucas** [comment]
Please try to bump this issue : https://github.com/SynoCommunity/spksrc/issues/2541
