### ISSUE TITLE
Download with Kindle Webbrowser

### ISSUE THREAD

**Issue by Offerel** [seblucas/cops#453]
I can browse COPS with the Kindle Webbrowser (in the menu on Amazon Kindle it appears as "Beta-Browser"). I can click on a .mobi and/or AZW3 file and it says "downloading" and "you can find the book at the startpage after succesfully download" after that i get a message that the file is downloaded successfully. But the book doesnt appear on the startpage. Is there any way to download ebooks directly with the build-in Kindle browser? Im using nginx as Webserver and COPS seems to work in the PC browser like Firefox.

**Comment by marioscube** [comment]
For my Kobo I need to:

You have to enable URL rewriting ($config['cops_use_url_rewriting']) in config_local.php to make it work.

I hope/think it's the same for Kindle browser.

**Comment by seblucas** [comment]
COPS has many users using Kindle so I can guess it works or it was working, I don't have any kindle to test myself can you try on another kindle ?

What model are you using ?

**Comment by Offerel** [comment]
I think, i have found the problem. I have now set the correct mime type in /etc/nginx/mime.types

This should contain a line like `application/x-mobipocket-ebook		mobi prc azw;` Now it seems to work as expected.

**Comment by seblucas** [comment]
Thanks for the report, I'll fix the docs soon
