### ISSUE TITLE
search-suggestions.js:1 Failed to load resource: net::ERR_FAILED

### ISSUE THREAD

**Issue by Torah** [seblucas/cops#454]
Failed with search-suggestions.js missing.

**Comment by horus68** [comment]
Can you please provide more details (just edit your initial issue) with your server, COPS version, where does it happens. Are you able to replicate in the demo: http://cops-demo.slucas.fr/index.php

**Comment by Torah** [comment]
Thank you for your reply!

I build it in LAMP container on Windows. And it failed with "Failed with search-suggestions.js missing." hint within all three versions of COPS.

**Comment by horus68** [comment]
I can't confirm that error just using your information.
You need to give detailed information on your situation

- "It failed" but when? When installing or when you performed a search (or any other particular action)?
- Is the COPS running? 
- What zip did you use to install?

On version to install: Use the latest `cops-1.1.3.zip` from https://github.com/seblucas/cops/releases

**Comment by Torah** [comment]
Thank you for your attention!

I install bt-panel on Win10 to setup a LAMP virtual environment to manage multiple php sites-development. When installing COPS via setup a new site in bt-panel, it hints failed without search-suggestions.js, both when using cops-1.1.3.zip or 1.1.2.zip. And I trully found no suggestions.js from the website root path. And that's all the situation.

I try to use bt-panel to setup LAMP virtual environment because it's comfortable to edit project files under win OS. You may use others as well. And the reason that I choose COPS rather than calibre-web on docker because I need to make markers when reading e-books, and it seems more comfortable under win OS. And why I don't setup calibre-web on docker using bt-panel on Win OS is that's a unstable way, the docker on bt-panel is easily go rupt when rebooting.

Thank you again for your patience and looking for your reply!

**Comment by horus68** [comment]
Hope someone can help you. I use Windows with Wamp and it works.
Maybe @seblucas can explain the alert on search-suggestions.js as this a never had that file too (but no error for me)

**Comment by woidi** [comment]
Hey Torah, did you already use bt-panel to successfully setup other sites on your system?
The "search-suggestions.js" is part of chrome browsers - could you try the setup using a different browser?

**Comment by Torah** [comment]
> Hey Torah, did you already use bt-panel to successfully setup other sites on your system?
> The "search-suggestions.js" is part of chrome browsers - could you try the setup using any chrome based browser?

Yes, I use bt-panel to successfully setup my own image hosting for coding.
![image](https://user-images.githubusercontent.com/6466559/63764285-0b175080-c8f9-11e9-9dbd-bf6c1513c507.png)
Strangely, I get this entry for cops today. I do nothing for cops recently. Strange... ...
![image](https://user-images.githubusercontent.com/6466559/63764368-3732d180-c8f9-11e9-9461-9d6d59fe6406.png)

**Comment by Torah** [comment]
Finished and Thank you!
