### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by johnmlife** [seblucas/cops#460]
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\cops

**Comment by horus68** [comment]
- Did you downloaded the compiled COPS install zip from here?
https://github.com/seblucas/cops/releases

- What versions are you using (Xampp / PHP / COPS)

**Comment by seblucas** [comment]
@horus68 already answered

Please read the README.md

**Comment by PetrusVermaak** [comment]
Hi Horus,

Would you ever consider converting COPS into a WordPress plugin? I can
contribute $100...

I have a library with over 30,000 books, and with WordPress is is so easy
to manage. User access, allow users to chat, allow them to only see certain
libraries.....

I definitely think it will dramatically increase COPS popularity as well!!



Kind Regards,

**Comment by horus68** [comment]
I'm not a developer, so I can't help you on that.
