### ISSUE TITLE
calibre v4 compatibility

### ISSUE THREAD

**Issue by Arthur60** [seblucas/cops#465]
Hi,

can anyone confirm COPS is already able to browse metadat.db from a fresh calibre v4.2 installation?

because cops diag page says metadata.db is unreachable though every thing seems okay to me in my settings. (php path, synology folder rights, etc.)

just tell me it runs fine and I'll dig further to find something else I could have done wrong.

Thank you very much.

**Comment by horus68** [comment]
COPS is working fine with Calibre v4.2
Your issue must be some other thing, so better to edit this issue title and detail your setup!

**Comment by Arthur60** [comment]
> COPS is working fine with Calibre v4.2
Thank you very much for this confirmation.

> Your issue must be some other thing, 
Thanks to your confirmation, I went back to my NAS administration panel and found out the read/write rights I'd put on my "calibre" folder had disappeared, for http and other users.
Very strange, I was so confident.
I think there's a step that wipe 'em out at some point during an installation.
Sorry, I don't mean to do it again from scratch in order to find out what really happens.

> so better to edit this issue title and detail your setup!
This not necessary now, thanks again :)

What I learnt is
- COPS works very well with my metadata.db, even though it was built with Calibre v4.2.
- Better check access rights twice than believing you set them once is enough ;)
