### ISSUE TITLE
problème avec pocketbook sur android

### ISSUE THREAD

**Issue by jajaX** [seblucas/cops#476]
salut,

merci déjà également ;)

ensuite, pour signaler un soucis avec la dernière version de pocketbook sur android.
j'arrive toujours à naviguer dans les rubriques de ma "bibliothèque réseau" pour le 1er niveau, mais impossible ensuite. j'appuie sur, par exemple, dernier ajout, mais rien ne se passe !
je peux donner plus de détails si besoin !

**Comment by marioscube** [comment]
See my answer here #486

**Comment by jajaX** [comment]
(sorry for my bad english !)

thanks, I modified my OPDS_renderer.php file with the info in this [post](https://github.com/seblucas/cops/issues/486#issuecomment-708694437)

solved !
