### ISSUE TITLE
XML has no style sheet

### ISSUE THREAD

**Issue by daveofca** [seblucas/cops#483]
New install on debian 10. Installed with composer 1.9 fix. All went well until web access shows only xml, with no style sheet attached. Nginx is the web server. Any help is greatly appreciated. Not sure if it's permissions or something I did wrong with nginx config...

**Comment by marioscube** [comment]
If you have a working config_local.php from a previous working installation of COPS copy it to the new one and try again.

Debian 10 with php 7.3 should work.
COPS should work
Nginx should work (I use apache, so can’t test)

If something is “wrong” with COPS in my experience it’s usually a typo in the config file.

**Comment by daveofca** [comment]
Removed nginx, installed apache, enabled php modules, downloaded release zip of cops, unzipped to html/books, it works! Thanks for your reply. Git was not a viable option on the install, but the zip did work. Thanks again!!!
