### ISSUE TITLE
error, cops on xampp 8.2

### ISSUE THREAD

**Issue by laurent-conte** [seblucas/cops#521]
Hi,

i setup COPS on XAMPP 8.2 with calibre 6.11.

I endup with this error when i try to reach the page:

Fatal error: Uncaught Error: Call to undefined function create_function() in C:\xampp\htdocs\cops\resources\doT-php\doT.php:94 Stack trace: #0 C:\xampp\htdocs\cops\index.php(62): doT->template('<!DOCTYPE html>...', NULL) #1 {main} thrown in C:\xampp\htdocs\cops\resources\doT-php\doT.php on line 94

Tried 2 different database, same error.

**Comment by Mikescher** [comment]
`create_function()` was removed in PHP 8 ( https://www.php.net/manual/en/function.create-function.php ).

You probably have to downgrade your PHP or use a docker container

**Comment by laurent-conte** [comment]
> `create_function()` was removed in PHP 8 ( https://www.php.net/manual/en/function.create-function.php ).
> 
> You probably have to downgrade your PHP or use a docker container

Donwgraded XAMPP to 7.1, worked right away! thanks a millon!
